package string;

/**
 * Created by simonla on 2016/12/17.
 * Have a good day!
 */
public class StringTest {

    public static void main(String[] args) {
        String i = "var ko=function(a){if(z.C&&!(8<=z.Vg))return a.offsetParent;var b=z.Ke(a),c=z.zg(a,\"position\"),d=\"fixed\"==c||\"absolute\"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(11==a.nodeType&&a.host&&(a=a.host),c=z.zg(a,\"position\"),d=d&&\"static\"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||\"fixed\"==c||\"absolute\"==c||\"relative\"==c))return a;return null};\n" +
                "var lo=function(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||lo(a,b,c,d))return!0;a=a.nextSibling}return!1};var mo=function(a,b){var c=a.parentNode;if(c==b)return-1;for(var d=b;d.parentNode!=c;)d=d.parentNode;return ao(d,a)};var no=function(a,b){return new z.Ge(a.x-b.x,a.y-b.y)};var oo=function(a){this.wv=a};\n" +
                "var po=function(a,b,c){if(null==b)c.push(\"null\");else{if(\"object\"==typeof b){if(z.ma(b)){a.serializeArray(b,c);return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push(\"{\");var d=\"\",f;for(f in b)if(Object.prototype.hasOwnProperty.call(b,f)){var g=b[f];\"function\"!=typeof g&&(c.push(d),qo(f,c),c.push(\":\"),po(a,a.wv?a.wv.call(b,f,g):g,c),d=\",\")}c.push(\"}\");return}}switch(typeof b){case \"string\":qo(b,c);break;case \"number\":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?\n" +
                "String(b):\"null\");break;case \"boolean\":c.push(String(b));break;case \"function\":c.push(\"null\");break;default:throw Error(\"Unknown type: \"+typeof b);}}};var qo=function(a,b){b.push('\"',a.replace(z.Tl,function(a){var b=ro[a];b||(b=\"\\\\u\"+(a.charCodeAt(0)|65536).toString(16).substr(1),ro[a]=b);return b}),'\"')};var so=function(a){var b=typeof a;return\"object\"==b&&a||\"function\"==b?\"o\"+z.ta(a):b.substr(0,1)+a};\n" +
                "var to=function(a,b){if(\"function\"==typeof a.every)return a.every(b,void 0);if(z.na(a)||z.oa(a))return z.eo(a,b,void 0);for(var c=z.Jd(a),d=z.Hd(a),f=d.length,g=0;g<f;g++)if(!b.call(void 0,d[g],c&&c[g],a))return!1;return!0};var uo=function(a){return a.kb&&\"function\"==typeof a.kb?a.kb():z.na(a)||z.oa(a)?a.length:z.co(a)};var vo=function(a){return z.Wa(a,\"\\x26\")?\"document\"in z.u?go(a):fo(a):a};\n" +
                "var wo=function(a,b,c,d,f){if(!(z.C||z.Gc||z.D&&z.E(\"525\")))return!0;if(z.Uc&&f)return z.io(a);if(f&&!d)return!1;z.pa(b)&&(b=z.mj(b));if(!c&&(17==b||18==b||z.Uc&&91==b))return!1;if((z.D||z.Gc)&&d&&c)switch(a){case 220:case 219:case 221:case 192:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:return!1}if(z.C&&d&&b==a)return!1;switch(a){case 13:return!0;case 27:return!(z.D||z.Gc)}return z.io(a)};\n" +
                "var xo=function(a){if(a.altKey&&!a.ctrlKey||a.metaKey||112<=a.keyCode&&123>=a.keyCode)return!1;switch(a.keyCode){case 18:case 20:case 93:case 17:case 40:case 35:case 27:case 36:case 45:case 37:case 224:case 91:case 144:case 12:case 34:case 33:case 19:case 255:case 44:case 39:case 145:case 16:case 38:case 252:case 224:case 92:return!1;case 0:return!z.B;default:return 166>a.keyCode||183<a.keyCode}};z.yo=function(a,b,c){c?z.ij(a,b):z.kj(a,b)};var zo=function(a,b){a.className=b};\n" +
                "var Ao=function(a){return z.fj(a,\"label\")};var Bo=function(a,b){var c=\"\";b&&(c=b.id);z.dj(a,\"activedescendant\",c)};var Co=function(a,b){switch(a){case 1:return b?\"disable\":\"enable\";case 2:return b?\"highlight\":\"unhighlight\";case 4:return b?\"activate\":\"deactivate\";case 8:return b?\"select\":\"unselect\";case 16:return b?\"check\":\"uncheck\";case 32:return b?\"focus\":\"blur\";case 64:return b?\"open\":\"close\"}throw Error(\"Invalid component state\");};\n" +
                "z.Do=function(a,b,c){c=c?null:a.getElementsByTagName(\"*\");if(z.fm){if(b=b?\"none\":\"\",a.style&&(a.style[z.fm]=b),c){a=0;for(var d;d=c[a];a++)d.style&&(d.style[z.fm]=b)}}else if(z.C||z.wg)if(b=b?\"on\":\"\",a.setAttribute(\"unselectable\",b),c)for(a=0;d=c[a];a++)d.setAttribute(\"unselectable\",b)};var Eo=function(a){var b=z.$n(a);a=z.Jg(a);return new z.sg(b.x,b.y,a.width,a.height)};var Fo=function(a,b,c){var d=z.$n(a);b instanceof z.Ge&&(c=b.y,b=b.x);z.Bg(a,a.offsetLeft+(b-d.x),a.offsetTop+(c-d.y))};\n" +
                "var Go=function(a,b){var c=b||z.Se(window.document),d;d=c||z.Se(window.document);var f=z.$n(a),g=z.$n(d),h=z.Ug(d);if(d==z.Se(window.document)){var k=f.x-d.scrollLeft,f=f.y-d.scrollTop;!z.C||10<=z.Vg||(k+=h.left,f+=h.top)}else k=f.x-g.x-h.left,f=f.y-g.y-h.top;var h=d.clientHeight-a.offsetHeight,g=d.scrollLeft,l=d.scrollTop,g=g+Math.min(k,Math.max(k-(d.clientWidth-a.offsetWidth),0)),l=l+Math.min(f,Math.max(f-h,0));d=new z.Ge(g,l);c.scrollLeft=d.x;c.scrollTop=d.y};\n" +
                "var Ho=function(a){for(var b=new z.rg(0,window.Infinity,window.Infinity,0),c=z.Ie(a),d=c.wa().body,f=c.wa().documentElement,g=z.Se(c.Ra);a=ko(a);)if(!(z.C&&0==a.clientWidth||z.D&&0==a.clientHeight&&a==d)&&a!=d&&a!=f&&\"visible\"!=z.zg(a,\"overflow\")){var h=z.$n(a),k=new z.Ge(a.clientLeft,a.clientTop);h.x+=k.x;h.y+=k.y;b.top=Math.max(b.top,h.y);b.right=Math.min(b.right,h.x+a.clientWidth);b.bottom=Math.min(b.bottom,h.y+a.clientHeight);b.left=Math.max(b.left,h.x)}d=g.scrollLeft;g=g.scrollTop;b.left=Math.max(b.left,\n" +
                "d);b.top=Math.max(b.top,g);c=z.Qe(c.bb());b.right=Math.min(b.right,d+c.width);b.bottom=Math.min(b.bottom,g+c.height);return 0<=b.top&&0<=b.left&&b.bottom>b.top&&b.right>b.left?b:null};var Io=function(a){var b=a.body;a=a.documentElement;return new z.Ge(b.scrollLeft||a.scrollLeft,b.scrollTop||a.scrollTop)};var Jo=function(a,b){var c=a.style[z.cb(b)];return\"undefined\"!==typeof c?c:a.style[z.ug(a,b)]||\"\"};\n" +
                "var Ko=function(a,b){var c=b.x<a.left?b.x-a.left:b.x>a.right?b.x-a.right:0,d=b.y<a.top?b.y-a.top:b.y>a.bottom?b.y-a.bottom:0;return Math.sqrt(c*c+d*d)};z.Lo=function(a,b){return z.vf(a,null,b,void 0)};z.Mo=function(a){var b=[];z.sf(a,b,!1);return b.join(\"\")};z.No=function(a,b){var c=[];lo(a,b,c,!1);return c};z.Oo=function(a){if(\"outerHTML\"in a)return a.outerHTML;var b=z.Ke(a).createElement(\"DIV\");b.appendChild(a.cloneNode(!0));return b.innerHTML};\n" +
                "var Po=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],f=window.Infinity;for(b=0;b<c;b++){for(var g=[],h=arguments[b];h;)g.unshift(h),h=h.parentNode;d.push(g);f=Math.min(f,g.length)}g=null;for(b=0;b<f;b++){for(var h=d[0][b],k=1;k<c;k++)if(h!=d[k][b])return g;g=h}return g};\n" +
                "var Qo=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(z.C&&!(9<=z.Vg)){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if(\"sourceIndex\"in a||a.parentNode&&\"sourceIndex\"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var f=a.parentNode,g=b.parentNode;return f==g?ao(a,b):!c&&z.nf(f,b)?-1*mo(a,b):!d&&z.nf(g,a)?mo(b,a):(c?a.sourceIndex:f.sourceIndex)-(d?b.sourceIndex:g.sourceIndex)}d=z.Ke(a);\n" +
                "c=d.cretion(a,b){var c=z.Md(a),d=new z.Ld;d.next=function(){for(;;){var a=c.next();if(b.call(void 0,a,void 0,c))return a}};return d};var cp=function(a,b,c){return Math.min(Math.max(a,b),c)};z.dp=function(a){var b={},c;for(c in a)b[a[c]]=c;return b};var ep=function(a,b){var c={},d;for(d in a)c[d]=b.call(void 0,a[d],d,a);return c};\n" +
                "var fp=function(a){for(var b=[],c=0;c<arguments.length;c++){var d=arguments[c];if(z.ma(d))for(var f=0;f<d.length;f+=8192)for(var g=z.yb(d,f,f+8192),g=fp.apply(null,g),h=0;h<g.length;h++)b.push(g[h]);else b.push(d)}return b};z.gp=function(a,b){for(var c=z.oa(a)?a.split(\"\"):a,d=a.length-1;0<=d;d--)if(d in c&&b.call(void 0,c[d],d,a))return d;return-1};var hp=function(a,b){var c=0;z.A(a,function(a,f,g){b.call(void 0,a,f,g)&&++c},void 0);return c};\n" +
                "z.ip=function(a){return function(){return!a.apply(this,arguments)}};z.jp=function(a){var b=arguments,c=b.length;return function(){for(var a=0;a<c;a++)if(!b[a].apply(this,arguments))return!1;return!0}};z.kp=function(a){var b=arguments,c=b.length;return function(){for(var a,f=0;f<c;f++)a=b[f].apply(this,arguments);return a}};z.lp=function(a,b){var c=arguments,d=c.length;return function(){var a;d&&(a=c[d-1].apply(this,arguments));for(var b=d-2;0<=b;b--)a=c[b].call(this,a);return a}};\n" +
                "v\";g=b[1]}else if(\"people\"===a.data[0]){a=Array.isArray(b[5])?b[5]:[b[5]];var h=a[0],k=d=\"\";h?k='\\x3cspan class\\x3d\"OrgIcon sprite-global-icon-org-14\"\\x3e\\x3c/span\\x3e':a[1]?(d=b[6]||\"\",k=a[2]?'\\x3cspan class\\x3d\"icon icon-badge icon-badge-id-an\"\\x3e\\x3c/span\\x3e':'\\x3cspan class\\x3d\"icon icon-badge icon-badge-identity\"\\x3e\\x3c/span\\x3e'):a[2]&&(d=\"优秀回答者\",k='\\x3cspan class\\x3d\"icon icon-badge icon-badge-best_answerer\"\\x3e\\x3c/span\\x3e');c.innerHTML='\\n        \\x3ca href\\x3d\"/'+(h?\"org\":\"people\")+\n" +
                "\"/\"+b[1]+'\" title\\x3d\"'+b[0]+'\"\\n          class\\x3d\"zm-ac-link zm-ac-link-people\"\\x3e\\n          \\x3cimg class\\x3d\"zm-item-img-avatar zg-left\" src\\x3d\"'+b[2]+'\"\\x3e\\n          \\x3cdiv class\\x3d\"zu-autocomplete-row-name\" title\\x3d\"'+b[0]+'\"\\x3e\\n            '+b[0]+k+'\\n          \\x3c/div\\x3e\\n          \\x3cdiv class\\x3d\"zu-autocomplete-row-description\"\\x3e\\n            \\x3cspan class\\x3d\"badge-summary\"\\x3e'+d+'\\x3c/span\\x3e\\n            \\x3cspan class\\x3d\"zg-gray-normal bio\"\\x3e'+b[4]+\"\\x3c/span\\x3e\\n          \\x3c/div\\x3e\\n        \\x3c/a\\x3e\\n      \";\n" +
                "f=\"User\";g=b[1]}else\"question\"===a.data[0]?(d=(0,window.parseInt)(b[3],10),c.innerHTML=(b[4]?'\\x3ca class\\x3d\"zg-star\" data-tooltip\\x3d\"s$b$优质问答\" href\\x3d\"/question/'+b[2]+'\"\\x3e\\x3c/a\\x3e':\"\")+['\\x3ca class\\x3d\"zm-ac-link\"','href\\x3d\"/question/'+b[2]+'\"\\x3e',b[0]].join(\"\")+('\\x3cspan class\\x3d\"zm-ac-gray\"\\x3e'+(d?d+\" 个回答\":\"还没有回答\")+\"\\x3c/span\\x3e\\x3c/a\\x3e\"),f=\"Question\",g=b[2].toString()):\"column\"===a.data[0]?(a=b[0],h=b[2].toString(),d=b[5],b=(0,window.parseInt)(b[3],10),k=\"\",0<b&&(k='\\x3cspan class\\x3d\"zm-ac-gray\"\\x3e '+\n" +
                "b+\" 人关注\\x3c/span\\x3e\"),c.innerHTML='\\n        \\x3ca class\\x3d\"zm-ac-link\" href\\x3d\"https://zhuanlan.zhihu.com/'+h+'\"\\x3e\\n          \\x3cimg class\\x3d\"zm-item-img-avatar column-avatar zg-left\" src\\x3d\"'+d+'\"\\x3e'+a+k+\"\\n        \\x3c/a\\x3e\\n      \",f=\"Column\",g=h):\"article\"===a.data[0]||\"promotion\"===a.data[0]?(a=a.data[0],h=b[0],d=b[2].toString(),b=(0,window.parseInt)(b[3],10),k=\"\",0<b&&(k='\\x3cspan class\\x3d\"zm-ac-gray\"\\x3e '+b+\" 个赞\\x3c/span\\x3e\"),c.innerHTML='\\n        \\x3ca class\\x3d\"zm-ac-link\" href\\x3d\"https://'+\n" +
                "(\"promotion\"===a?\"promotion\":\"zhuanlan\")+\".zhihu.com/p/\"+d+'\"\\x3e\\n          '+h+k+\"\\n        \\x3c/a\\x3e\\n      \",f=\"promotion\"===a?\"Ad\":\"Post\",g=d):\"search_link\"===a.data[0]?(c.innerHTML='\\x3ca href\\x3d\"/search?q\\x3d'+b[0]+'\\x26type\\x3dquestion\" data-za-element-name\\x3d\"ViewAll\"\\x3e查看全部搜索结果\\x3ci class\\x3d\"zg-icon arrow\"\\x3e\\x3c/i\\x3e\\x3c/a\\x3e',z.V.add(c,\"zu-autocomplete-row-search-link\")):\"plain_text\"===a.data[0]?c.innerHTML=b[0]:\"sina\"===a.data[0]&&(c.innerHTML=['\\x3ca href\\x3d\"javascript:;\" title\\x3d\"'+\n" +
                "b[0]+'\"\\x3e','\\qr=function(a,b,c,d,f){if(2!=b.length||2!=c.length)throw Error(\"Start and end points must be 2D\");pr.apply(this,arguments)};var rr=function(a,b,c,d,f){if(2!=b.length||2!=c.length)throw Error(\"Start and end points must be 2D\");pr.apply(this,arguments)};var sr=function(a,b,c,d,f){pr.call(this,a,[b],[c],d,f)};var tr=function(a,b,c,d,f){pr.call(this,a,[b],[c],d,f)};\n" +
                "var ur=function(a,b,c,d,face(/^\\s+/,\"\").replace(/\\s+$/,\"\"):\"\"};var Er=function(a){return a?a.replace(/<[^>]+>/g,\"\"):\"\"};var Fr=function(){return'\\x3ca href\\x3d\"javascript:;\" class\\x3d\"zu-edit-button\" name\\x3d\"edit\"\\x3e\\x3ci class\\x3d\"zu-edit-button-icon\"\\x3e\\x3c/i\\x3e修改\\x3c/a\\x3e'};z.Gr=function(a,b){z.P(a,!0);z.P(b,!1)};\n" +
                "var Hr=function(a,b,c){var d;a&&(b=(0,window.$)(a).data(\"animation\")||new yr(a,[255,255,150],b||[255,255,255],c||2E3),(0,window.$)(a).data(\"animation\",b),1==b.N&&b.stop(!0),d=a.style.backgroundColor,z.ld(b,\"end\",function(){z.tg(this.element,\"background-color\",d)},!1,b),b.play())};z.Ir=function(a,b,c){a&&(Jr&&window.document[Kr]?z.F(window.document,Lr,function f(){window.document[Kr]||(Hr(a,b,c),z.md(window.document,Lr,f))}):Hr(a,b,c))};\n" +
                "var Mr=function(a){var b=0,c=0;do c=a.indexOf(\"?\",c),-1!==c&&(b++,c+=1);while(-1!==c);return b};\n" +
                "var Nr=function(a,b,c){b=z.yb(a.data,1);if(\"topic\"===a.data[0]){a=(b[2]?'\\x3cimg class\\x3d\"zm-item-img-avatar zg-left\" src\\x3d\"'+b[2]+'\"\\x3e':\"\")+'\\x3cspan class\\x3d\"zu-autocomplete-row-name'+(b[3]?\"\":\" zu-autocomplete-row-name-info\")+'\" title\\x3d\"'+b[0]+'\"\\x3e'+b[0]+\"\\x3c/span\\x3e\";var d=5<b.length&&b[5];4<=b.length&&(a+='\\x3cspan class\\x3d\"zg-gray-normal zu-autocomplete-row-description\"\\x3e',b[4]||d?(d&&(a+=\"又称 \"+b[5]),b[4]&&d&&(a+=\"，\"),b[4]&&(a+=b[4]+\" 人关注\")):a+=\"\\x26nbsp;\",a+=\"\\x3c/span\\x3e\");\n" +
                "c.innerHTML=a}else if(\"people\"===a.data[0]){a=Array.isArray(b[5])?b[5]:[b[5]];var f=d=\"\";a[0]?f='\\x3cspan class\\x3d\"OrgIcon sprite-global-icon-org-14\"\\x3e\\x3c/span\\x3e':a[1]?(d=b[6]||\"\",f=a[2]?'\\x3cspan class\\x3d\"icon icon-badge icon-badge-id-an\"\\x3e\\x3c/span\\x3e':'\\x3cspan class\\x3d\"icon icon-badge icon-badge-identity\"\\x3e\\x3c/span\\x3e'):a[2]&&(d=\"优秀回答者\",f='\\x3cspan class\\x3d\"icon icon-badge icon-badge-best_answerer\"\\x3e\\x3c/span\\x3e');c.innerHTML='\\n      \\x3cimg class\\x3d\"zm-item-img-avatar zg-left\" src\\x3d\"'+\n" +
                "b[2]+'\"\\x3e\\n      \\x3cdiv class\\x3d\"zu-autocomplete-row-name\" title\\x3d\"'+b[0]+'\"\\x3e\\n        '+b[0]+f+'\\n      \\x3c/div\\x3e\\n      \\x3cdiv class\\x3d\"zu-autocomplete-row-description\"\\x3e\\n        \\x3cspan class\\x3d\"badge-summary\"\\x3e'+d+'\\x3c/span\\x3e\\n        \\x3cspan class\\x3d\"zg-gray-normal bio\"\\x3e'+(b[4]||\"\\x26nbsp;\")+\"\\x3c/span\\x3e\\n      \\x3c/div\\x3e\\n    \"}else\"question\"===a.data[0]?c.innerHTML=b[0]+'\\x3cspan class\\x3d\"zm-ac-gray\"\\x3e问题\\x3c/span\\x3e':\"plain_text\"===a.data[0]?(c.innerHTML=\n" +
                "a.data[1],z.V.add(c,b[1])):\"sina\"===a.data[0]&&(c.innerHTML=b[0])};\n" +
                "var Or=function(a,b,c){var d;b=z.yb(a.data,1);var f=void 0,g;if(\"topic\"===a.data[0]){a=[\"\\x3ca \",' style\\x3d\"display:block\" href\\x3d\"/topic/'+b[1]+'\"\\x3e\\x3cspan class\\x3d\"zm-item-tag\"\\x3e',b[0],\"\\x3c/span\\x3e\"].join(\"\");d=6<b.length&&b[6];if(b[5]||d){a+='\\x3cspan class\\x3d\"zm-ac-gray\"\\x3e';var h=[];d&&h.push(\"又称 \"+b[6]);(d=(0,window.parseInt)(b[5],10))&&h.push(d+\" 个精华问答\");a+=h.join(\"，\");a+=\"\\x3c/span\\x3e\"}else a+='\\x3cspan class\\x3d\"zm-ac-gray\" \\x3e\\x26nbsp;\\x3c/span\\x3e';c.innerHTML=a+\"\\x3c/a\\x3e\";\n" +
                "f=\"Topic\";g=b[1]}else if(\"people\"===a.data[0]){a=Array.isArray(b[5])?b[5]:[b[5]];var h=a[0],k=d=\"\";h?k='\\x3cspan class\\x3d\"OrgIcon sprite-global-icon-org-14\"\\x3e\\x3c/span\\x3e':a[1]?(d=b[6]||\"\",k=a[2]?'\\x3cspan class\\x3d\"icon icon-badge icon-badge-id-an\"\\x3e\\x3c/span\\x3e':'\\x3cspan class\\x3d\"icon icon-badge icon-badge-identity\"\\x3e\\x3c/span\\x3e'):a[2]&&(d=\"优秀回答者\",k='\\x3cspan class\\x3d\"icon icon-badge icon-badge-best_answerer\"\\x3e\\x3c/span\\x3e');c.innerHTML='\\n        \\x3ca href\\x3d\"/'+(h?\"org\":\"people\")+\n" +
                "\"/\"+b[1]+'\" title\\x3d\"'+b[0]+'\"\\n          class\\x3d\"zm-ac-link zm-ac-link-people\"\\x3e\\n          \\x3cimg class\\x3d\"zm-item-img-avatar zg-left\" src\\x3d\"'+b[2]+'\"\\x3e\\n          \\x3cdiv class\\x3d\"zu-autocomplete-row-name\" title\\x3d\"'+b[0]+'\"\\x3e\\n            '+b[0]+k+'\\n          \\x3c/div\\x3e\\n          \\x3cdiv class\\x3d\"zu-autocomplete-row-description\"\\x3e\\n            \\x3cspan class\\x3d\"badge-summary\"\\x3e'+d+'\\x3c/span\\x3e\\n            \\x3cspan class\\x3d\"zg-gray-normal bio\"\\x3e'+b[4]+\"\\x3c/span\\x3e\\n          \\x3c/div\\x3e\\n        \\x3c/a\\x3e\\n      \";\n" +
                "f=\"User\";g=b[1]}else\"question\"===a.data[0]?(d=(0,window.parseInt)(b[3],10),c.innerHTML=(b[4]?'\\x3ca class\\x3d\"zg-star\" data-tooltip\\x3d\"s$b$优质问答\" href\\x3d\"/question/'+b[2]+'\"\\x3e\\x3c/a\\x3e':\"\")+['\\x3ca class\\x3d\"zm-ac-link\"','href\\x3d\"/question/'+b[2]+'\"\\x3e',b[0]].join(\"\")+('\\x3cspan class\\x3d\"zm-ac-gray\"\\x3e'+(d?d+\" 个回答\":\"还没有回答\")+\"\\x3c/span\\x3e\\x3c/a\\x3e\"),f=\"Question\",g=b[2].toString()):\"column\"===a.data[0]?(a=b[0],h=b[2].toString(),d=b[5],b=(0,window.parseInt)(b[3],10),k=\"\",0<b&&(k='\\x3cspan class\\x3d\"zm-ac-gray\"\\x3e '+\n" +
                "b+\" 人关注\\x3c/span\\x3e\"),c.innerHTML='\\n        \\x3ca class\\x3d\"zm-ac-link\" href\\x3d\"https://zhuanlan.zhihu.com/'+h+'\"\\x3e\\n          \\x3cimg class\\x3d\"zm-item-img-avatar column-avatar zg-left\" src\\x3d\"'+d+'\"\\x3e'+a+k+\"\\n        \\x3c/a\\x3e\\n      \",f=\"Column\",g=h):\"article\"===a.data[0]||\"promotion\"===a.data[0]?(a=a.data[0],h=b[0],d=b[2].toString(),b=(0,window.parseInt)(b[3],10),k=\"\",0<b&&(k='\\x3cspan class\\x3d\"zm-ac-gray\"\\x3e '+b+\" 个赞\\x3c/span\\x3e\"),c.innerHTML='\\n        \\x3ca class\\x3d\"zm-ac-link\" href\\x3d\"https://'+\n" +
                "(\"promotion\"===a?\"promotion\":\"zhuanlan\")+\".zhihu.com/p/\"+d+'\"\\x3e\\n          '+h+k+\"\\n        \\x3c/a\\x3e\\n      \",f=\"promotion\"===a?\"Ad\":\"Post\",g=d):\"search_link\"===a.data[0]?(c.innerHTML='\\x3ca href\\x3d\"/search?q\\x3d'+b[0]+'\\x26type\\x3dquestion\" data-za-element-name\\x3d\"ViewAll\"\\x3e查看全部搜索结果\\x3ci class\\x3d\"zg-icon arrow\"\\x3e\\x3c/i\\x3e\\x3c/a\\x3e',z.V.add(c,\"zu-autocomplete-row-search-link\")):\"plain_text\"===a.data[0]?c.innerHTML=b[0]:\"sina\"===a.data[0]&&(c.innerHTML=['\\x3ca href\\x3d\"javascript:;\" title\\x3d\"'+\n" +
                "b[0]+'\"\\x3e','\\x3cimg class\\x3d\"zm-item-img-avatar\" src\\x3d\"'+b[2]+'\" /\\x3e',b[0],\"\\x3c/a\\x3e\"].join(\"\"));f&&g&&c&&z.S.mb(c,{module:f+\"Item\",index:\"\"},function(){return{card:{card_type:\"Content\",content:{type:f,token:g}}}});(0,window.$)(\"a\",c).click(function(a){a.preventDefault()})};z.Pr=function(a,b,c){for(c=c||\"A\";null!=b&&b!==a;){if(b.tagName===c)return b;b=b.parentNode}return null};z.Qr=function(a){this.RT=a;this.data=new z.Qd};var Rr=function(a){return(a=z.Dr(a))?a.length:0};\n" +
                "var Sr=function(a,b,c,d){window._gaq||(window._gaq=[]);c&&(c=\"\"+c);d&&(d=(0,window.parseInt)(d,10));window._gaq.push([\"_trackEvent\",a,b,c,d]);z.Li&&Tr(\"trackEvent(deprecated)\",z.vb(arguments))};var Ur=function(a){return(a=String(a).toLowerCase())?z.ob([\".jpg\",\".jpeg\",\".png\"],function(b){return z.up(a,b)}):!1};var Vr=function(a,b){function c(b){return a.getElementsByTagName(b).length}var d=[\"img\",\"embed\"];return b&&z.ob(d,c)?!1:!z.lp(z.Wr,z.ab,z.qf)(a)};\n" +
                "z.Xr=function(a,b){var c=window.$.extend({all:!1},z.Xr.defaults,b||{}),d=(0,window.$)(a).get(0).getBoundingClientRect();return!c.all&&(d.bottom<c.paddingTop||d.bottom>(0,window.$)(window).height())||c.all&&(d.top<c.paddingTop||d.bottom>(0,window.$)(window).height())?!1:!0};\n" +
                "z.Yr=function(a,b){if(a){\"number\"===window.$.type(b)&&(b={offsetTop:b});var c=window.$.extend({JD:z.Xr},Zr,b||{});if(!c.JD(a,c)){var d=(0,window.$)(a).offset().top-c.paddingTop-c.offsetTop||0;c.px?(0,window.$)(window.document.documentElement).add(window.document.body).animate({scrollTop:d}):(0,window.$)(window).scrollTop(d)}}};var $r=function(a){(0,window.$)(a.target.M.h).off(\"click.disable-a\").on(\"click.disable-a\",\"a\",function(a){a.preventDefault()})};\n" +
                "z.as=function(a,b){var c=null;return function(){var d=this,f=arguments;(0,window.clearTimeout)(c);c=(0,window.setTimeout)(function(){b.apply(d,f)},a)}};var bs=function(a,b){var c=a.getBoundingClientRect(),d=z.Rg(window.document.body).top;if(0<c.top-d)b&&b();else{var f=a.offsetHeight,g=Io(window.document).y,h=z.Qe().height;b&&b();var k=a.offsetHeight;window.scrollTo(0,g+(c.bottom<h?k-f:c.top-d))}};\n" +
                "z.cs=function(a){return 1E4>a?a.toString():1E6>a?(0,window.parseInt)(a/1E3)+\"K\":1E9>a?(0,window.parseInt)(a/1E6)+\"M\":(0,window.parseInt)(a/1E9)+\"G\"};z.ds=function(a){z.G.call(this);this.aJ=null;this.Id=a;this.o().g(this.Id,[\"input\",\"propertychange\"],this.BM);es(this,!0);z.V.add(this.Id,\"zu-seamless-input-origin-element\")};var es=function(a,b){fs(a);if(a.Fg){var c=a.Id.value;if(b||a.aJ!==c)a.aJ=c,a.Fg.value=c,c=z.Ug(a.Id),a.Id.style.height=z.Cg(a.Fg.scrollHeight+c.top+c.bottom,!0),a.dispatchEvent(\"change\")}};\n" +
                "var fs=function(a){if(!qr=function(a,b,c,d,f){if(2!=b.length||2!=c.length)throw Error(\"Start and end points must be 2D\");pr.apply(this,arguments)};var rr=function(a,b,c,d,f){if(2!=b.length||2!=c.length)throw Error(\"Start and end points must be 2D\");pr.apply(this,arguments)};var sr=function(a,b,c,d,f){pr.call(this,a,[b],[c],d,f)};var tr=function(a,b,c,d,f){pr.call(this,a,[b],[c],d,f)};\n" +
                "var ur=function(a,b,c,d,f){z.pa(b)&&(b=[b]);z.pa(c)&&(c=[c]);pr.call(this,a,b,c,d,f);if(1!=b.length||1!=c.length)throw Error(\"Start and end points must be 1D\");this.qu=vr};var wr=function(a,b,c){ur.call(this,a,1,0,b,c)};var xr=function(a,b,c){ur.call(this,a,0,1,b,c)};var yr=function(a,b,c,d,f){if(3!=b.length||3!=c.length)throw Error(\"Start and end points must be 3D\");pr.apply(this,arguments)};var zr=function(){return window.$.Deferred(function(a){(0,window.setTimeout)(a.resolve,2E3)}).promise()};\n" +
                "var Ar=function(a,b){var c=z.No(a,function(a){return 3===a.nodeType&&!z.tp(a.nodeValue)})[0];c&&(c.nodeValue=b)};z.Br=function(a,b){var c=new wr(a,500);b&&z.F(c,\"finish\",(0,z.t)(function(){z.N(this)},a));c.play()};z.Cr=function(a,b,c,d){\"bottom\"===d&&(d=\"b\");var f=\"\";!1!==c&&(f='data-hovercard\\x3d\"t$'+(d||\"t\")+\"$\"+a[1]+'\"');return[\"\\x3ca \",f,' class\\x3d\"',b||\"zm-item-tag\",'\" href\\x3d\"/topic/',a[1],'\"\\x3e',a[0],\"\\x3c/a\\x3e\"].join(\"\")};\n" +
                "z.Dr=function(a){return a?a.replace(/^\\s+/,\"\").replace(/\\s+$/,\"\"):\"\"};var Er=function(a){return a?a.replace(/<[^>]+>/g,\"\"):\"\"};var Fr=function(){return'\\x3ca href\\x3d\"javascript:;\" class\\x3d\"zu-edit-button\" name\\x3d\"edit\"\\x3e\\x3ci class\\x3d\"zu-edit-button-icon\"\\x3e\\x3c/i\\x3e修改\\x3c/a\\x3e'};z.Gr=function(a,b){z.P(a,!0);z.P(b,!1)};\n" +
                "var Hr=function(a,b,c){var d;a&&(b=(0,window.$)(a).data(\"animation\")||new yr(a,[255,255,150],b||[255,255,255],c||2E3),(0,window.$)(a).data(\"animation\",b),1==b.N&&b.stop(!0),d=a.style.backgroundColor,z.ld(b,\"end\",function(){z.tg(this.element,\"background-color\",d)},!1,b),b.play())};z.Ir=function(a,b,c){a&&(Jr&&window.document[Kr]?z.F(window.document,Lr,function f(){window.document[Kr]||(Hr(a,b,c),z.md(window.document,Lr,f))}):Hr(a,b,c))};\n" +
                "var Mr=function(a){var b=0,c=0;do c=a.indexOf(\"?\",c),-1!==c&&(b++,c+=1);while(-1!==c);return b};\n" +
                "var Nr=function(a,b,c){b=z.yb(a.data,1);if(\"topic\"===a.data[0]){a=(b[2]?'\\x3cimg class\\x3d\"zm-item-img-avatar zg-left\" src\\x3d\"'+b[2]+'\"\\x3e':\"\")+'\\x3cspan class\\x3d\"zu-autocomplete-row-name'+(b[3]?\"\":\" zu-autocomplete-row-name-info\")+'\" title\\x3d\"'+b[0]+'\"\\x3e'+b[0]+\"\\x3c/span\\x3e\";var d=5<b.length&&b[5];4<=b.length&&(a+='\\x3cspan class\\x3d\"zg-gray-normal zu-autocomplete-row-description\"\\x3e',b[4]||d?(d&&(a+=\"又称 \"+b[5]),b[4]&&d&&(a+=\"，\"),b[4]&&(a+=b[4]+\" 人关注\")):a+=\"\\x26nbsp;\",a+=\"\\x3c/span\\x3e\");\n" +
                "c.innerHTML=a}else if(\"people\"===a.data[0]){a=Array.isArray(b[5])?b[5]:[b[5]];var f=d=\"\";a[0]?f='\\x3cspan class\\x3d\"OrgIcon sprite-global-icon-org-14\"\\x3e\\x3c/span\\x3e':a[1]?(d=b[6]||\"\",f=a[2]?'\\x3cspan class\\x3d\"icon icon-badge icon-badge-id-an\"\\x3e\\x3c/span\\x3e':'\\x3cspan class\\x3d\"icon icon-badge icon-badge-identity\"\\x3e\\x3c/span\\x3e'):a[2]&&(d=\"优秀回答者\",f='\\x3cspan class\\x3d\"icon icon-badge icon-badge-best_answerer\"\\x3e\\x3c/span\\x3e');c.innerHTML='\\n      \\x3cimg class\\x3d\"zm-item-img-avatar zg-left\" src\\x3d\"'+\n" +
                "b[2]+'\"\\x3e\\n      \\x3cdiv class\\x3d\"zu-autocomplete-row-name\" title\\x3d\"'+b[0]+'\"\\x3e\\n        '+b[0]+f+'\\n      \\x3c/div\\x3e\\n      \\x3cdiv class\\x3d\"zu-autocomplete-row-description\"\\x3e\\n        \\x3cspan class\\x3d\"badge-summary\"\\x3e'+d+'\\x3c/span\\x3e\\n        \\x3cspan class\\x3d\"zg-gray-normal bio\"\\x3e'+(b[4]||\"\\x26nbsp;\")+\"\\x3c/span\\x3e\\n      \\x3c/div\\x3e\\n    \"}else\"question\"===a.data[0]?c.innerHTML=b[0]+'\\x3cspan class\\x3d\"zm-ac-gray\"\\x3e问题\\x3c/span\\x3e':\"plain_text\"===a.data[0]?(c.innerHTML=\n" +
                "a.data[1],z.V.add(c,b[1])):\"sina\"===a.data[0]&&(c.innerHTML=b[0])};\n" +
                "var Or=function(a,b,c){var d;b=z.yb(a.data,1);var f=void 0,g;if(\"topic\"===a.data[0]){a=[\"\\x3ca \",' style\\x3d\"display:block\" href\\x3d\"/topic/'+b[1]+'\"\\x3e\\x3cspan class\\x3d\"zm-item-tag\"\\x3e',b[0],\"\\x3c/span\\x3e\"].join(\"\");d=6<b.length&&b[6];if(b[5]||d){a+='\\x3cspan class\\x3d\"zm-ac-gray\"\\x3e';var h=[];d&&h.push(\"又称 \"+b[6]);(d=(0,window.parseInt)(b[5],10))&&h.push(d+\" 个精华问答\");a+=h.join(\"，\");a+=\"\\x3c/span\\x3e\"}else a+='\\x3cspan class\\x3d\"zm-ac-gray\" \\x3e\\x26nbsp;\\x3c/span\\x3e';c.innerHTML=a+\"\\x3c/a\\x3e\";\n" +
                "f=\"Topic\";g=b[1]}else if(\"people\"===a.data[0]){a=Array.isArray(b[5])?b[5]:[b[5]];var h=a[0],k=d=\"\";h?k='\\x3cspan class\\x3d\"OrgIcon sprite-global-icon-org-14\"\\x3e\\x3c/span\\x3e':a[1]?(d=b[6]||\"\",k=a[2]?'\\x3cspan class\\x3d\"icon icon-badge icon-badge-id-an\"\\x3e\\x3c/span\\x3e':'\\x3cspan class\\x3d\"icon icon-badge icon-badge-identity\"\\x3e\\x3c/span\\x3e'):a[2]&&(d=\"优秀回答者\",k='\\x3cspan class\\x3d\"icon icon-badge icon-badge-best_answerer\"\\x3e\\x3c/span\\x3e');c.innerHTML='\\n        \\x3ca href\\x3d\"/'+(h?\"org\":\"people\")+\n" +
                "\"/\"+b[1]+'\" title\\x3d\"'+b[0]+'\"\\n          class\\x3d\"zm-ac-link zm-ac-link-people\"\\x3e\\n          \\x3cimg class\\x3d\"zm-item-img-avatar zg-left\" src\\x3d\"'+b[2]+'\"\\x3e\\n          \\x3cdiv class\\x3d\"zu-autocomplete-row-name\" title\\x3d\"'+b[0]+'\"\\x3e\\n            '+b[0]+k+'\\n          \\x3c/div\\x3e\\n          \\x3cdiv class\\x3d\"zu-autocomplete-row-description\"\\x3e\\n            \\x3cspan class\\x3d\"badge-summary\"\\x3e'+d+'\\x3c/span\\x3e\\n            \\x3cspan class\\x3d\"zg-gray-normal bio\"\\x3e'+b[4]+\"\\x3c/span\\x3e\\n          \\x3c/div\\x3e\\n        \\x3c/a\\x3e\\n      \";\n" +
                "f=\"User\";g=b[1]}else\"question\"===a.data[0]?(d=(0,window.parseInt)(b[3],10),c.innerHTML=(b[4]?'\\x3ca class\\x3d\"zg-star\" data-tooltip\\x3d\"s$b$优质问答\" href\\x3d\"/question/'+b[2]+'\"\\x3e\\x3c/a\\x3e':\"\")+['\\x3ca class\\x3d\"zm-ac-link\"','href\\x3d\"/question/'+b[2]+'\"\\x3e',b[0]].join(\"\")+('\\x3cspan class\\x3d\"zm-ac-gray\"\\x3e'+(d?d+\" 个回答\":\"还没有回答\")+\"\\x3c/span\\x3e\\x3c/a\\x3e\"),f=\"Question\",g=b[2].toString()):\"column\"===a.data[0]?(a=b[0],h=b[2].toString(),d=b[5],b=(0,window.parseInt)(b[3],10),k=\"\",0<b&&(k='\\x3cspan class\\x3d\"zm-ac-gray\"\\x3e '+\n" +
                "b+\" 人关注\\x3c/span\\x3e\"),c.innerHTML='\\n        \\x3ca class\\x3d\"zm-ac-link\" href\\x3d\"https://zhuanlan.zhihu.com/'+h+'\"\\x3e\\n          \\x3cimg class\\x3d\"zm-item-img-avatar column-avatar zg-left\" src\\x3d\"'+d+'\"\\x3e'+a+k+\"\\n        \\x3c/a\\x3e\\n      \",f=\"Column\",g=h):\"article\"===a.data[0]||\"promotion\"===a.data[0]?(a=a.data[0],h=b[0],d=b[2].toString(),b=(0,window.parseInt)(b[3],10),k=\"\",0<b&&(k='\\x3cspan class\\x3d\"zm-ac-gray\"\\x3e '+b+\" 个赞\\x3c/span\\x3e\"),c.innerHTML='\\n        \\x3ca class\\x3d\"zm-ac-link\" href\\x3d\"https://'+\n" +
                "(\"promotion\"===a?\"promotion\":\"zhuanlan\")+\".zhihu.com/p/\"+d+'\"\\x3e\\n          '+h+k+\"\\n        \\x3c/a\\x3e\\n      \",f=\"promotion\"===a?\"Ad\":\"Post\",g=d):\"search_link\"===a.data[0]?(c.innerHTML='\\x3ca href\\x3d\"/search?q\\x3d'+b[0]+'\\x26type\\x3dquestion\" data-za-element-name\\x3d\"ViewAll\"\\x3e查看全部搜索结果\\x3ci class\\x3d\"zg-icon arrow\"\\x3e\\x3c/i\\x3e\\x3c/a\\x3e',z.V.add(c,\"zu-autocomplete-row-search-link\")):\"plain_text\"===a.data[0]?c.innerHTML=b[0]:\"sina\"===a.data[0]&&(c.innerHTML=['\\x3ca href\\x3d\"javascript:;\" title\\x3d\"'+\n" +
                "b[0]+'\"\\x3e','\\x3cimg class\\x3d\"zm-item-img-avatar\" src\\x3d\"'+b[2]+'\" /\\x3e',b[0],\"\\x3c/a\\x3e\"].join(\"\"));f&&g&&c&&z.S.mb(c,{module:f+\"Item\",index:\"\"},function(){return{card:{card_type:\"Content\",content:{type:f,token:g}}}});(0,window.$)(\"a\",c).click(function(a){a.preventDefault()})};z.Pr=function(a,b,c){for(c=c||\"A\";null!=b&&b!==a;){if(b.tagName===c)return b;b=b.parentNode}return null};z.Qr=function(a){this.RT=a;this.data=new z.Qd};var Rr=function(a){return(a=z.Dr(a))?a.length:0};\n" +
                "var Sr=function(a,b,c,d){window._gaq||(window._gaq=[]);c&&(c=\"\"+c);d&&(d=(0,window.parseInt)(d,10));window._gaq.push([\"_trackEvent\",a,b,c,d]);z.Li&&Tr(\"trackEvent(deprecated)\",z.vb(arguments))};var Ur=function(a){return(a=String(a).toLowerCase())?z.ob([\".jpg\",\".jpeg\",\".png\"],function(b){return z.up(a,b)}):!1};var Vr=function(a,b){function c(b){return a.getElementsByTagName(b).length}var d=[\"img\",\"embed\"];return b&&z.ob(d,c)?!1:!z.lp(z.Wr,z.ab,z.qf)(a)};\n" +
                "z.Xr=function(a,b){var c=window.$.extend({all:!1},z.Xr.defaults,b||{}),d=(0,window.$)(a).get(0).getBoundingClientRect();return!c.all&&(d.bottom<c.paddingTop||d.bottom>(0,window.$)(window).height())||c.all&&(d.top<c.paddingTop||d.bottom>(0,window.$)(window).height())?!1:!0};\n" +
                "z.Yr=function(a,b){if(a){\"number\"===window.$.type(b)&&(b={offsetTop:b});var c=window.$.extend({JD:z.Xr},Zr,b||{});if(!c.JD(a,c)){var d=(0,window.$)(a).offset().top-c.paddingTop-c.offsetTop||0;c.px?(0,window.$)(window.document.documentElement).add(window.document.body).animate({scrollTop:d}):(0,window.$)(window).scrollTop(d)}}};var $r=function(a){(0,window.$)(a.target.M.h).off(\"click.disable-a\").on(\"click.disable-a\",\"a\",function(a){a.preventDefault()})};\n" +
                "z.as=function(a,b){var c=null;return function(){var d=this,f=arguments;(0,window.clearTimeout)(c);c=(0,window.setTimeout)(function(){b.apply(d,f)},a)}};var bs=function(a,b){var c=a.getBoundingClientRect(),d=z.Rg(window.document.body).top;if(0<c.top-d)b&&b();else{var f=a.offsetHeight,g=Io(window.document).y,h=z.Qe().height;b&&b();var k=a.offsetHeight;window.scrollTo(0,g+(c.bottom<h?k-f:c.top-d))}};\n" +
                "z.cs=function(a){return 1E4>a?a.toString():1E6>a?(0,window.parseInt)(a/1E3)+\"K\":1E9>a?(0,window.parseInt)(a/1E6)+\"M\":(0,window.parseInt)(a/1E9)+\"G\"};z.ds=function(a){z.G.call(this);this.aJ=null;this.Id=a;this.o().g(this.Id,[\"input\",\"propertychange\"],this.BM);es(this,!0);z.V.add(this.Id,\"zu-seamless-input-origin-element\")};var es=function(a,b){fs(a);if(a.Fg){var c=a.Id.value;if(b||a.aJ!==c)a.aJ=c,a.Fg.value=c,c=z.Ug(a.Id),a.Id.style.height=z.Cg(a.Fg.scrollHeight+c.top+c.bottom,!0),a.dispatchEvent(\"change\")}};\n" +
                "var fs=function(a){if(!a.Fg&&0!==z.jo(a.Id).width){var b=z.M(\"div\",{style:\"overflow:hiddenposition:relativeheight:0\"},a.Fg=z.M(\"textarea\",{rows:1,className:\"zu-seamless-input-mock-element\"}));window.document.body.appendChild(b);z.Db(\"paddingTop paddingBottom fontFamily fontSize fontWeight fontStyle letterSpacing textTransform wordSpacing textIndent lineHeight width white-space\".split(\" \"),function(a){this.Fg.style[a]=z.xg(this.Id,a)},a)}};var gs=function(a){this.tx=a};\n" +
                "var hs=function(a,b){a&&(a.tabIndex=b?0:-1)};var is=function(a,b,c){if(c)for(var d=c.firstChild,f;d&&d.parentNode==c;){f=d.nextSibling;if(1==d.nodeType){var g=a.So(d);g&&(g.h=d,b.isEnabled()||g.cb(!1),b.K(g),g.w(d))}else d.nodeValue&&\"\"!=(0,z.ab)(d.nodeValue)||c.removeChild(d);d=f}};z.js=function(a,b,c){z.Q.call(this,c);this.M=b||gs.ba();this.Wb=a||this.M.eH()};\n" +
                "var ks=function(a,b){var c=a.o(),d=a.hc();b?c.g(d,\"focus\",a.we).g(d,\"blur\",a.od).g(a.wt(),\"key\",a.ic):c.oa(d,\"focus\",a.we).oa(d,\"blur\",a.od).oa(a.wt(),\"key\",a.ic)};var ls=function(a,b){var c=b.m(),c=c.id||(c.id=b.ve());a.ih||(a.ih={});a.ih[c]=b};var ms=function(a){return z.ch(a,a.Ya)};z.ns=function(a){os(a,function(a,c){return(a+1)%c},z.bh(a)-1)};var ps=function(a){os(a,function(a,c){a--;return 0>a?c-1:a},0)};var qs=function(a){os(a,function(a,c){return(a+1)%c},a.Ya)};\n" +
                "var rs=function(a){os(a,function(a,c){a--;return 0>a?c-1:a},a.Ya)};var os=function(a,b,c){c=0>c?Qn(a,a.tc):c;var d=z.bh(a);c=b.call(a,c,d);for(var f=0;f<=d;){var g=z.ch(a,c);if(g&&a.nF(g)){a.Gb(c);break}f++;c=b.call(a,c,d)}};var ss=function(){z.Q.call(this);this.vw=[]};z.ts=function(a,b){this.Oa=a||[];this.GD=!b};var us=function(a,b,c){var d=[];if(\"\"!=a){a=z.Xa(a);a=new RegExp(\"(^|\\\\W+)\"+a,\"i\");for(var f=0;f<c.length&&d.length<b;f++){var g=c[f];String(g).match(a)&&d.push(g)}}return d};\n" +
                "var vs=function(a,b,c){for(var d=[],f=0;f<c.length;f++){var g=c[f],h=a.toLowerCase(),k=String(g).toLowerCase(),l=0;if(-1!=k.indexOf(h))l=(0,window.parseInt)((k.indexOf(h)/4).toString(),10);else for(var p=h.split(\"\"),q=-1,w=10,I=0,K;K=p[I];I++)K=k.indexOf(K),K>q?(q=K-q-1,q>w-5&&(q=w-5),l+=q,q=K):(l+=w,w+=5);l<6*h.length&&d.push({FY:g,qL:l,index:f})}d.sort(function(a,b){var c=a.qL-b.qL;return 0!=c?c:a.index-b.index});a=[];for(I=0;I<b&&I<d.length;I++)a.push(d[I].FY);return a};\n" +
                "z.ws=function(a,b,c){z.G.call(this);this.ae=a;this.Xf=c;this.M=b;z.F(b,[xs,z.ys,zs,z.As],this.handleEvent,!1,this);this.ec=null;this.Oa=[];this.Ah=-1;this.kd=0;this.oe=this.Lc=null;this.tI={}};z.Bs=function(a){for(var b=a.kd+a.Oa.length-1,c=a.Ah,d=0;d<a.Oa.length;d++){if(c>=a.kd&&c<b)c++;else if(-1==c)c=a.kd;else if(a.JE&&c==b){a.zg(-1);break}else if(a.aN&&c==b)c=a.kd;else break;if(a.zg(c))break}};\n" +
                "var Cs=function(a){for(var b=a.kd+a.Oa.length-1,c=a.Ah,d=0;d<a.Oa.length;d++){if(c>a.kd)c--;else if(a.JE&&c==a.kd){a.zg(-1);break}else if(!a.aN||-1!=c&&c!=a.kd)break;else c=b;if(a.zg(c))break}};z.Ds=function(a){a.iI()||window.setTimeout((0,z.t)(a.iI,a),10)};var Es=function(a,b){var c=b-a.kd;return 0>c||c>=a.Oa.length?-1:c};\n" +
                "z.Fs=function(a){var b=0,c=0;if(Gs(a))b=a.selectionStart,c=-1;else if(z.C){var d=Hs(a),f=d[0],d=d[1];if(f.inRange(d)){f.setEndPoint(\"EndToStart\",d);if(\"textarea\"==a.type){d.duplicate();b=a=f.text;for(c=!1;!c;)0==f.compareEndPoints(\"StartToEnd\",f)?c=!0:(f.moveEnd(\"character\",-1),f.text==a?b+=\"\\r\\n\":c=!0);f=[b.length,-1];return f}b=f.text.length;c=-1}}return[b,c]};\n" +
                "z.Is=function(a,b){if(Gs(a))a.selectionStart=b,a.selectionEnd=b;else if(z.C){b=Js(a,b);var c=a.createTextRange();c.collapse(!0);c.move(\"character\",b);c.select()}};var Hs=function(a){var b=a.ownerDocument||a.document,c=b.selection.createRange();\"textarea\"==a.type?(b=b.body.createTextRange(),b.moveToElementText(a)):b=a.createTextRange();return[b,c]};var Js=function(a,b){\"textarea\"==a.type&&(b=z.Ka(a.value.substring(0,b)).length);return b};var Gs=function(a){try{return\"number\"==typeof a.selectionStart}catch(b){return!1}};\n" +
                "z.Ks=function(a,b,c,d){z.xc.call(this);d=d||150;this.Rm=null!=c?c:!0;this.Qq=a||\",;\";this.fQ=this.Qq.substring(0,1);a=this.Rm?\"[\\\\s\"+this.Qq+\"]+\":\"[\\\\s]+\";this.uM=new RegExp(\"^\"+a+\"|\"+a+\"$\",\"g\");this.dY=new RegExp(\"\\\\s*[\"+this.Qq+\"]$\");this.gJ=b||\"\";this.TW=!1;this.SW=this.Rm;this.la=0<d?new z.td(d):null;this.nc=new z.xd(this);this.Yw=new z.xd(this);this.Eb=new Sp;this.YI=-1};\n" +
                "var Ls=function(a,b,c){if(z.ja(c)?c:a.Rm){c=Ms(a,a.X(),z.Fs(a.ob)[0]);var d=Ns(a,a.X());a.dY.test(b)||(b=z.op(b)+a.fQ);a.JZ&&(0==c||z.tp(d[c-1])||(b=\" \"+b),c==d.length-1&&(b+=\" \"));if(b!=d[c]){d[c]=b;b=a.ob;(z.B||z.C&&z.E(\"9\"))&&b.blur();b.value=d.join(\"\");for(var f=0,g=0;g<=c;g++)f+=d[g].length;b.focus();c=f;d=a.ob;b=c;Gs(d)?d.selectionStart=b:z.C&&(f=Hs(d),g=f[0],g.inRange(f[1])&&(b=Js(d,b),g.collapse(!0),g.move(\"character\",b),g.select()));d=a.ob;Gs(d)?d.selectionEnd=c:z.C&&(f=Hs(d),b=f[1],f[0].inRange(b)&&\n" +
                "(c=Js(d,c),d=Js(d,z.Fs(d)[0]),b.collapse(!0),b.moveEnd(\"character\",c-d),b.select()))}}else a.Da(b);a.rC=!0};var Os=function(a,b){var c=a.Rm&&b.charCode&&-1!=a.Qq.indexOf(String.fromCharCode(b.charCode));a.fY&&c&&a.update();return a.eY&&c&&a.Y.ij()?(b.preventDefault(),!0):!1};var Ps=function(a){a.Eb.attach(a.ob);a.nc.g(a.Eb,\"key\",a.tq);a.nc.g(a.ob,\"mousedown\",a.gK);z.C&&a.nc.g(a.ob,\"keypress\",a.dK)};\n" +
                "var Qs=function(a,b){a.Yw.removeAll();a.Y&&z.Ds(a.Y);b!=a.ob&&(a.ob=b,a.la&&(a.la.start(),a.nc.g(a.la,\"tick\",a.wq)),a.Vp=a.X(),Ps(a))};var Rs=function(a){a.uj&&(a.uj=!1,a.nc.oa(a.ob,\"keypress\",a.eK),a.nc.oa(a.ob,\"keyup\",a.fK))};var Ms=function(a,b,c){a=Ns(a,b);if(c==b.length)return a.length-1;for(var d=b=0,f=0;d<a.length&&f<=c;d++)f+=a[d].length,b=d;return b};\n" +
                "var Ns=function(a,b){if(!a.Rm)return[b];for(var c=String(b).split(\"\"),d=[],f=[],g=0,h=!1;g<c.length;g++)a.gJ&&-1!=a.gJ.indexOf(c[g])?(a.dR&&!h&&(d.push(f.join(\"\")),f.length=0),f.push(c[g]),h=!h):h||-1==a.Qq.indexOf(c[g])?f.push(c[g]):(f.push(c[g]),d.push(f.join(\"\")),f.length=0);d.push(f.join(\"\"));return d};z.Ss=function(a,b,c){z.xc.call(this);this.zD=a;this.GD=!b;this.da=new z.de(c)};\n" +
                "z.Ts=function(a,b,c,d,f,g,h,k,l){var p=Us(c),q=Eo(a),w=Ho(a);w&&q.uA(new z.sg(w.left,w.top,w.right-w.left,w.bottom-w.top));var w=z.Ie(a),I=z.Ie(c);if(w.wa()!=I.wa()){var K=w.wa().body;var I=I.bb(),O=new z.Ge(0,0),ba=z.Te(z.Ke(K));if(z.Oc(ba,\"parent\")){var Ua=K;do{var Sa=ba==I?z.$n(Ua):z.Gg(Ua);O.x+=Sa.x;O.y+=Sa.y}while(ba&&ba!=I&&ba!=ba.parent&&(Ua=ba.frameElement)&&(ba=ba.parent))}K=no(O,z.$n(K));!z.C||9<=z.Vg||Un(w)||(K=no(K,z.xf(w)));q.left+=K.x;q.top+=K.y}a=Vs(a,b);q=new z.Ge(a&2?q.left+q.width:\n" +
                "q.left,a&1?q.top+q.height:q.top);q=no(q,p);f&&(q.x+=(a&2?-1:1)*f.x,q.y+=(a&1?-1:1)*f.y);var ya;if(h)if(l)ya=l;else if(ya=Ho(c))ya.top-=p.y,ya.right-=p.x,ya.bottom-=p.y,ya.left-=p.x;return Ws(q,c,d,g,ya,h,k)};\n" +
                "var Us=function(a){var b;if(a=a.offsetParent){var c=\"HTML\"==a.tagName||\"BODY\"==a.tagName;c&&\"static\"==z.Ag(a)||(b=z.$n(a),c||(c=(c=z.Og(a))&&z.B?-a.scrollLeft:!c||z.Ll&&z.E(\"8\")||\"visible\"==z.zg(a,\"overflowX\")?a.scrollLeft:a.scrollWidth-a.clientWidth-a.scrollLeft,b=no(b,new z.Ge(c,a.scrollTop))))}return b||new z.Ge};\n" +
                "var Ws=function(a,b,c,d,f,g,h){a=a.clone();var k=Vs(b,c);c=z.Jg(b);h=h?h.clone():c.clone();a=a.clone();h=h.clone();var l=0;if(d||0!=k)k&2?a.x-=h.width+(d?d.right:0):d&&(a.x+=d.left),k&1?a.y-=h.height+(d?d.bottom:0):d&&(a.y+=d.top);if(g){if(f){d=a;k=h;l=0;65==(g&65)&&(d.x<f.left||d.x>=f.right)&&(g&=-2);132==(g&132)&&(d.y<f.top||d.y>=f.bottom)&&(g&=-5);d.x<f.left&&g&1&&(d.x=f.left,l|=1);if(g&16){var p=d.x;d.x<f.left&&(d.x=f.left,l|=4);d.x+k.width>f.right&&(k.width=Math.min(f.right-d.x,p+k.width-f.left),\n" +
                "k.width=Math.max(k.width,0),l|=4)}d.a.Fg&&0!==z.jo(a.Id).width){var b=z.M(\"div\",{style:\"overflow:hiddenposition:relativeheight:0\"},a.Fg=z.M(\"textarea\",{rows:1,className:\"zu-seamless-input-mock-element\"}));window.document.body.appendChild(b);z.Db(\"paddingTop paddingBottom fontFamily fontSize fontWeight fontStyle letterSpacing textTransform wordSpacing textIndent lineHeight width white-space\".split(\" \"),function(a){this.Fg.style[a]=z.xg(this.Id,a)},a)}};var gs=function(a){this.tx=a};\n" +
                "var hs=function(a,b){a&&(a.tabIndex=b?0:-1)};var is=function(a,b,c){if(c)for(var d=c.firstChild,f;d&&d.parentNode==c;){f=d.nextSibling;if(1==d.nodeType){var g=a.So(d);g&&(g.h=d,b.isEnabled()||g.cb(!1),b.K(g),g.w(d))}else d.nodeValue&&\"\"!=(0,z.ab)(d.nodeValue)||c.removeChild(d);d=f}};z.js=function(a,b,c){z.Q.call(this,c);this.M=b||gs.ba();this.Wb=a||this.M.eH()};\n" +
                "var ks=function(a,b){var c=a.o(),d=a.hc();b?c.g(d,\"focus\",a.we).g(d,\"blur\",a.od).g(a.wt(),\"key\",a.ic):c.oa(d,\"focus\",a.we).oa(d,\"blur\",a.od).oa(a.wt(),\"key\",a.ic)};var ls=function(a,b){var c=b.m(),c=c.id||(c.id=b.ve());a.ih||(a.ih={});a.ih[c]=b};var ms=function(a){return z.ch(a,a.Ya)};z.ns=function(a){os(a,function(a,c){return(a+1)%c},z.bh(a)-1)};var ps=function(a){os(a,function(a,c){a--;return 0>a?c-1:a},0)};var qs=function(a){os(a,function(a,c){return(a+1)%c},a.Ya)};\n" +
                "var rs=function(a){os(a,function(a,c){a--;return 0>a?c-1:a},a.Ya)};var os=function(a,b,c){c=0>c?Qn(a,a.tc):c;var d=z.bh(a);c=b.call(a,c,d);for(var f=0;f<=d;){var g=z.ch(a,c);if(g&&a.nF(g)){a.Gb(c);break}f++;c=b.call(a,c,d)}};var ss=function(){z.Q.call(this);this.vw=[]};z.ts=function(a,b){this.Oa=a||[];this.GD=!b};var us=function(a,b,c){var d=[];if(\"\"!=a){a=z.Xa(a);a=new RegExp(\"(^|\\\\W+)\"+a,\"i\");for(var f=0;f<c.length&&d.length<b;f++){var g=c[f];String(g).match(a)&&d.push(g)}}return d};\n" +
                "var vs=function(a,b,c){for(var d=[],f=0;f<c.length;f++){var g=c[f],h=a.toLowerCase(),k=String(g).toLowerCase(),l=0;if(-1!=k.indexOf(h))l=(0,window.parseInt)((k.indexOf(h)/4).toString(),10);else for(var p=h.split(\"\"),q=-1,w=10,I=0,K;K=p[I];I++)K=k.indexOf(K),K>q?(q=K-q-1,q>w-5&&(q=w-5),l+=q,q=K):(l+=w,w+=5);l<6*h.length&&d.push({FY:g,qL:l,index:f})}d.sort(function(a,b){var c=a.qL-b.qL;return 0!=c?c:a.index-b.index});a=[];for(I=0;I<b&&I<d.length;I++)a.push(d[I].FY);return a};\n" +
                "z.ws=function(a,b,c){z.G.call(this);this.ae=a;this.Xf=c;this.M=b;z.F(b,[xs,z.ys,zs,z.As],this.handleEvent,!1,this);this.ec=null;this.Oa=[];this.Ah=-1;this.kd=0;this.oe=this.Lc=null;this.tI={}};z.Bs=function(a){for(var b=a.kd+a.Oa.length-1,c=a.Ah,d=0;d<a.Oa.length;d++){if(c>=a.kd&&c<b)c++;else if(-1==c)c=a.kd;else if(a.JE&&c==b){a.zg(-1);break}else if(a.aN&&c==b)c=a.kd;else break;if(a.zg(c))break}};\n" +
                "var Cs=function(a){for(var b=a.kd+a.Oa.length-1,c=a.Ah,d=0;d<a.Oa.length;d++){if(c>a.kd)c--;else if(a.JE&&c==a.kd){a.zg(-1);break}else if(!a.aN||-1!=c&&c!=a.kd)break;else c=b;if(a.zg(c))break}};z.Ds=function(a){a.iI()||window.setTimeout((0,z.t)(a.iI,a),10)};var Es=function(a,b){var c=b-a.kd;return 0>c||c>=a.Oa.length?-1:c};\n" +
                "z.Fs=function(a){var b=0,c=0;if(Gs(a))b=a.selectionStart,c=-1;else if(z.C){var d=Hs(a),f=d[0],d=d[1];if(f.inRange(d)){f.setEndPoint(\"EndToStart\",d);if(\"textarea\"==a.type){d.duplicate();b=a=f.text;for(c=!1;!c;)0==f.compareEndPoints(\"StartToEnd\",f)?c=!0:(f.moveEnd(\"character\",-1),f.text==a?b+=\"\\r\\n\":c=!0);f=[b.length,-1];return f}b=f.text.length;c=-1}}return[b,c]};\n" +
                "z.Is=function(a,b){if(Gs(a))a.selectionStart=b,a.selectionEnd=b;else if(z.C){b=Js(a,b);var c=a.createTextRange();c.collapse(!0);c.move(\"character\",b);c.select()}};var Hs=function(a){var b=a.ownerDocument||a.document,c=b.selection.createRange();\"textarea\"==a.type?(b=b.body.createTextRange(),b.moveToElementText(a)):b=a.createTextRange();return[b,c]};var Js=function(a,b){\"textarea\"==a.type&&(b=z.Ka(a.value.substring(0,b)).length);return b};var Gs=function(a){try{return\"number\"==typeof a.selectionStart}catch(b){return!1}};\n" +
                "z.Ks=function(a,b,c,d){z.xc.call(this);d=d||150;this.Rm=null!=c?c:!0;this.Qq=a||\",;\";this.fQ=this.Qq.substring(0,1);a=this.Rm?\"[\\\\s\"+this.Qq+\"]+\":\"[\\\\s]+\";this.uM=new RegExp(\"^\"+a+\"|\"+a+\"$\",\"g\");this.dY=new RegExp(\"\\\\s*[\"+this.Qq+\"]$\");this.gJ=b||\"\";this.TW=!1;this.SW=this.Rm;this.la=0<d?new z.td(d):null;this.nc=new z.xd(this);this.Yw=new z.xd(this);this.Eb=new Sp;this.YI=-1};\n" +
                "var Ls=function(a,b,c){if(z.ja(c)?c:a.Rm){c=Ms(a,a.X(),z.Fs(a.ob)[0]);var d=Ns(a,a.X());a.dY.test(b)||(b=z.op(b)+a.fQ);a.JZ&&(0==c||z.tp(d[c-1])||(b=\" \"+b),c==d.length-1&&(b+=\" \"));if(b!=d[c]){d[c]=b;b=a.ob;(z.B||z.C&&z.E(\"9\"))&&b.blur();b.value=d.join(\"\");for(var f=0,g=0;g<=c;g++)f+=d[g].length;b.focus();c=f;d=a.ob;b=c;Gs(d)?d.selectionStart=b:z.C&&(f=Hs(d),g=f[0],g.inRange(f[1])&&(b=Js(d,b),g.collapse(!0),g.move(\"character\",b),g.select()));d=a.ob;Gs(d)?d.selectionEnd=c:z.C&&(f=Hs(d),b=f[1],f[0].inRange(b)&&\n" +
                "(c=Js(d,c),d=Js(d,z.Fs(d)[0]),b.collapse(!0),b.moveEnd(\"character\",c-d),b.select()))}}else a.Da(b);a.rC=!0};var Os=function(a,b){var c=a.Rm&&b.charCode&&-1!=a.Qq.indexOf(String.fromCharCode(b.charCode));a.fY&&c&&a.update();return a.eY&&c&&a.Y.ij()?(b.preventDefault(),!0):!1};var Ps=function(a){a.Eb.attach(a.ob);a.nc.g(a.Eb,\"key\",a.tq);a.nc.g(a.ob,\"mousedown\",a.gK);z.C&&a.nc.g(a.ob,\"keypress\",a.dK)};\n" +
                "var Qs=function(a,b){a.Yw.removeAll();a.Y&&z.Ds(a.Y);b!=a.ob&&(a.ob=b,a.la&&(a.la.start(),a.nc.g(a.la,\"tick\",a.wq)),a.Vp=a.X(),Ps(a))};var Rs=function(a){a.uj&&(a.uj=!1,a.nc.oa(a.ob,\"keypress\",a.eK),a.nc.oa(a.ob,\"keyup\",a.fK))};var Ms=function(a,b,c){a=Ns(a,b);if(c==b.length)return a.length-1;for(var d=b=0,f=0;d<a.length&&f<=c;d++)f+=a[d].length,b=d;return b};\n" +
                "var Ns=function(a,b){if(!a.Rm)return[b];for(var c=String(b).split(\"\"),d=[],f=[],g=0,h=!1;g<c.length;g++)a.gJ&&-1!=a.gJ.indexOf(c[g])?(a.dR&&!h&&(d.push(f.join(\"\")),f.length=0),f.push(c[g]),h=!h):h||-1==a.Qq.indexOf(c[g])?f.push(c[g]):(f.push(c[g]),d.push(f.join(\"\")),f.length=0);d.push(f.join(\"\"));return d};z.Ss=function(a,b,c){z.xc.call(this);this.zD=a;this.GD=!b;this.da=new z.de(c)};\n" +
                "z.Ts=function(a,b,c,d,f,g,h,k,l){var p=Us(c),q=Eo(a),w=Ho(a);w&&q.uA(new z.sg(w.left,w.top,w.right-w.left,w.bottom-w.top));var w=z.Ie(a),I=z.Ie(c);if(w.wa()!=I.wa()){var K=w.wa().body;var I=I.bb(),O=new z.Ge(0,0),ba=z.Te(z.Ke(K));if(z.Oc(ba,\"parent\")){var Ua=K;do{var Sa=ba==I?z.$n(Ua):z.Gg(Ua);O.x+=Sa.x;O.y+=Sa.y}while(ba&&ba!=I&&ba!=ba.parent&&(Ua=ba.frameElement)&&(ba=ba.parent))}K=no(O,z.$n(K));!z.C||9<=z.Vg||Un(w)||(K=no(K,z.xf(w)));q.left+=K.x;q.top+=K.y}a=Vs(a,b);q=new z.Ge(a&2?q.left+q.width:\n" +
                "q.left,a&1?q.top+q.height:q.top);q=no(q,p);f&&(q.x+=(a&2?-1:1)*f.x,q.y+=(a&1?-1:1)*f.y);var ya;if(h)if(l)ya=l;else if(ya=Ho(c))ya.top-=p.y,ya.right-=p.x,ya.bottom-=p.y,ya.left-=p.x;return Ws(q,c,d,g,ya,h,k)};\n" +
                "var Us=function(a){var b;if(a=a.offsetParent){var c=\"HTML\"==a.tagName||\"BODY\"==a.tagName;c&&\"static\"==z.Ag(a)||(b=z.$n(a),c||(c=(c=z.Og(a))&&z.B?-a.scrollLeft:!c||z.Ll&&z.E(\"8\")||\"visible\"==z.zg(a,\"overflowX\")?a.scrollLeft:a.scrollWidth-a.clientWidth-a.scrollLeft,b=no(b,new z.Ge(c,a.scrollTop))))}return b||new z.Ge};\n" +
                "var Ws=function(a,b,c,d,f,g,h){a=a.clone();var k=Vs(b,c);c=z.Jg(b);h=h?h.clone():c.clone();a=a.clone();h=h.clone();var l=0;if(d||0!=k)k&2?a.x-=h.width+(d?d.right:0):d&&(a.x+=d.left),k&1?a.y-=h.height+(d?d.bottom:0):d&&(a.y+=d.top);if(g){if(f){d=a;k=h;l=0;65==(g&65)&&(d.x<f.left||d.x>=f.right)&&(g&=-2);132==(g&132)&&(d.y<f.top||d.y>=f.bottom)&&(g&=-5);d.x<f.left&&g&1&&(d.x=f.left,l|=1);if(g&16){var p=d.x;d.x<f.left&&(d.x=f.left,l|=4);d.x+k.width>f.right&&(k.width=Math.min(f.right-d.x,p+k.width-f.left),\n" +
                "k.width=Math.max(k.width,0),l|=4)}d.x3cimg class\\x3d\"zm-item-img-avatar\" src\\x3d\"'+b[2]+'\" /\\x3e',b[0],\"\\x3c/a\\x3e\"].join(\"\"));f&&g&&c&&z.S.mb(c,{module:f+\"Item\",index:\"\"},function(){return{card:{card_type:\"Content\",content:{type:f,token:g}}}});(0,window.$)(\"a\",c).click(function(a){a.preventDefault()})};z.Pr=function(a,b,c){for(c=c||\"A\";null!=b&&b!==a;){if(b.tagName===c)return b;b=b.parentNode}return null};z.Qr=function(a){this.RT=a;this.data=new z.Qd};var Rr=function(a){return(a=z.Dr(a))?a.length:0};\n" +
                "var Sr=function(a,b,c,d){window._gaq||(window._gaq=[]);c&&(c=\"\"+c);d&&(d=(0,window.parseInt)(d,10));window._gaq.push([\"_trackEvent\",a,b,c,d]);z.Li&&Tr(\"trackEvent(deprecated)\",z.vb(arguments))};var Ur=function(a){return(a=String(a).toLowerCase())?z.ob([\".jpg\",\".jpeg\",\".png\"],function(b){return z.up(a,b)}):!1};var Vr=function(a,b){function c(b){return a.getElementsByTagName(b).length}var d=[\"img\",\"embed\"];return b&&z.ob(d,c)?!1:!z.lp(z.Wr,z.ab,z.qf)(a)};\n" +
                "z.Xr=function(a,b){var c=window.$.extend({all:!1},z.Xr.defaults,b||{}),d=(0,window.$)(a).get(0).getBoundingClientRect();return!c.all&&(d.bottom<c.paddingTop||d.bottom>(0,window.$)(window).height())||c.all&&(d.top<c.paddingTop||d.bottom>(0,window.$)(window).height())?!1:!0};\n" +
                "z.Yr=function(a,b){if(a){\"number\"===window.$.type(b)&&(b={offsetTop:b});var c=window.$.extend({JD:z.Xr},Zr,b||{});if(!c.JD(a,c)){var d=(0,window.$)(a).offset().top-c.paddingTop-c.offsetTop||0;c.px?(0,window.$)(window.document.documentElement).add(window.document.body).animate({scrollTop:d}):(0,window.$)(window).scrollTop(d)}}};var $r=function(a){(0,window.$)(a.target.M.h).off(\"click.disable-a\").on(\"click.disable-a\",\"a\",function(a){a.preventDefault()})};\n" +
                "z.as=function(a,b){var c=null;return function(){var d=this,f=arguments;(0,window.clearTimeout)(c);c=(0,window.setTimeout)(function(){b.apply(d,f)},a)}};var bs=function(a,b){var c=a.getBoundingClientRect(),d=z.Rg(window.document.body).top;if(0<c.top-d)b&&b();else{var f=a.offsetHeight,g=Io(window.document).y,h=z.Qe().height;b&&b();var k=a.offsetHeight;window.scrollTo(0,g+(c.bottom<h?k-f:c.top-d))}};\n" +
                "z.cs=function(a){return 1E4>a?a.toString():1E6>a?(0,window.parseInt)(a/1E3)+\"K\":1E9>a?(0,window.parseInt)(a/1E6)+\"M\":(0,window.parseInt)(a/1E9)+\"G\"};z.ds=function(a){z.G.call(this);this.aJ=null;this.Id=a;this.o().g(this.Id,[\"input\",\"propertychange\"],this.BM);es(this,!0);z.V.add(this.Id,\"zu-seamless-input-origin-element\")};var es=function(a,b){fs(a);if(a.Fg){var c=a.Id.value;if(b||a.aJ!==c)a.aJ=c,a.Fg.value=c,c=z.Ug(a.Id),a.Id.style.height=z.Cg(a.Fg.scrollHeight+c.top+c.bottom,!0),a.dispatchEvent(\"change\")}};\n" +
                "var fs=function(a){if(!a.Fg&&0!==z.jo(a.Id).width){var b=z.M(\"div\",{style:\"overflow:hiddenposition:relativeheight:0\"},a.Fg=z.M(\"textarea\",{rows:1,className:\"zu-seamless-input-mock-element\"}));window.document.body.appendChild(b);z.Db(\"paddingTop paddingBottom fontFamily fontSize fontWeight fontStyle letterSpacing textTransform wordSpacing textIndent lineHeight width white-space\".split(\" \"),function(a){this.Fg.style[a]=z.xg(this.Id,a)},a)}};var gs=function(a){this.tx=a};\n" +
                "var hs=function(a,b){a&&(a.tabIndex=b?0:-1)};var is=function(a,b,c){if(c)for(var d=c.firstChild,f;d&&d.parentNode==c;){f=d.nextSibling;if(1==d.nodeType){var g=a.So(d);g&&(g.h=d,b.isEnabled()||g.cb(!1),b.K(g),g.w(d))}else d.nodeValue&&\"\"!=(0,z.ab)(d.nodeValue)||c.removeChild(d);d=f}};z.js=function(a,b,c){z.Q.call(this,c);this.M=b||gs.ba();this.Wb=a||this.M.eH()};\n" +
                "var ks=function(a,b){var c=a.o(),d=a.hc();b?c.g(d,\"focus\",a.we).g(d,\"blur\",a.od).g(a.wt(),\"key\",a.ic):c.oa(d,\"focus\",a.we).oa(d,\"blur\",a.od).oa(a.wt(),\"key\",a.ic)};var ls=function(a,b){var c=b.m(),c=c.id||(c.id=b.ve());a.ih||(a.ih={});a.ih[c]=b};var ms=function(a){return z.ch(a,a.Ya)};z.ns=function(a){os(a,function(a,c){return(a+1)%c},z.bh(a)-1)};var ps=function(a){os(a,function(a,c){a--;return 0>a?c-1:a},0)};var qs=function(a){os(a,function(a,c){return(a+1)%c},a.Ya)};\n" +
                "var rs=function(a){os(a,function(a,c){a--;return 0>a?c-1:a},a.Ya)};var os=function(a,b,c){c=0>c?Qn(a,a.tc):c;var d=z.bh(a);c=b.call(a,c,d);for(var f=0;f<=d;){var g=z.ch(a,c);if(g&&a.nF(g)){a.Gb(c);break}f++;c=b.call(a,c,d)}};var ss=function(){z.Q.call(this);this.vw=[]};z.ts=function(a,b){this.Oa=a||[];this.GD=!b};var us=function(a,b,c){var d=[];if(\"\"!=a){a=z.Xa(a);a=new RegExp(\"(^|\\\\W+)\"+a,\"i\");for(var f=0;f<c.length&&d.length<b;f++){var g=c[f];String(g).match(a)&&d.push(g)}}return d};\n" +
                "var vs=function(a,b,c){for(var d=[],f=0;f<c.length;f++){var g=c[f],h=a.toLowerCase(),k=String(g).toLowerCase(),l=0;if(-1!=k.indexOf(h))l=(0,window.parseInt)((k.indexOf(h)/4).toString(),10);else for(var p=h.split(\"\"),q=-1,w=10,I=0,K;K=p[I];I++)K=k.indexOf(K),K>q?(q=K-q-1,q>w-5&&(q=w-5),l+=q,q=K):(l+=w,w+=5);l<6*h.length&&d.push({FY:g,qL:l,index:f})}d.sort(function(a,b){var c=a.qL-b.qL;return 0!=c?c:a.index-b.index});a=[];for(I=0;I<b&&I<d.length;I++)a.push(d[I].FY);return a};\n" +
                "z.ws=function(a,b,c){z.G.call(this);this.ae=a;this.Xf=c;this.M=b;z.F(b,[xs,z.ys,zs,z.As],this.handleEvent,!1,this);this.ec=null;this.Oa=[];this.Ah=-1;this.kd=0;this.oe=this.Lc=null;this.tI={}};z.Bs=function(a){for(var b=a.kd+a.Oa.length-1,c=a.Ah,d=0;d<a.Oa.length;d++){if(c>=a.kd&&c<b)c++;else if(-1==c)c=a.kd;else if(a.JE&&c==b){a.zg(-1);break}else if(a.aN&&c==b)c=a.kd;else break;if(a.zg(c))break}};\n" +
                "var Cs=function(a){for(var b=a.kd+a.Oa.length-1,c=a.Ah,d=0;d<a.Oa.length;d++){if(c>a.kd)c--;else if(a.JE&&c==a.kd){a.zg(-1);break}else if(!a.aN||-1!=c&&c!=a.kd)break;else c=b;if(a.zg(c))break}};z.Ds=function(a){a.iI()||window.setTimeout((0,z.t)(a.iI,a),10)};var Es=function(a,b){var c=b-a.kd;return 0>c||c>=a.Oa.length?-1:c};\n" +
                "z.Fs=function(a){var b=0,c=0;if(Gs(a))b=a.selectionStart,c=-1;else if(z.C){var d=Hs(a),f=d[0],d=d[1];if(f.inRange(d)){f.setEndPoint(\"EndToStart\",d);if(\"textarea\"==a.type){d.duplicate();b=a=f.text;for(c=!1;!c;)0==f.compareEndPoints(\"StartToEnd\",f)?c=!0:(f.moveEnd(\"character\",-1),f.text==a?b+=\"\\r\\n\":c=!0);f=[b.length,-1];return f}b=f.text.length;c=-1}}return[b,c]};\n" +
                "z.Is=function(a,b){if(Gs(a))a.selectionStart=b,a.selectionEnd=b;else if(z.C){b=Js(a,b);var c=a.createTextRange();c.collapse(!0);c.move(\"character\",b);c.select()}};var Hs=function(a){var b=a.ownerDocument||a.document,c=b.selection.createRange();\"textarea\"==a.type?(b=b.body.createTextRange(),b.moveToElementText(a)):b=a.createTextRange();return[b,c]};var Js=function(a,b){\"textarea\"==a.type&&(b=z.Ka(a.value.substring(0,b)).length);return b};var Gs=function(a){try{return\"number\"==typeof a.selectionStart}catch(b){return!1}};\n" +
                "z.Ks=function(a,b,c,d){z.xc.call(this);d=d||150;this.Rm=null!=c?c:!0;this.Qq=a||\",;\";this.fQ=this.Qq.substring(0,1);a=this.Rm?\"[\\\\s\"+this.Qq+\"]+\":\"[\\\\s]+\";this.uM=new RegExp(\"^\"+a+\"|\"+a+\"$\",\"g\");this.dY=new RegExp(\"\\\\s*[\"+this.Qq+\"]$\");this.gJ=b||\"\";this.TW=!1;this.SW=this.Rm;this.la=0<d?new z.td(d):null;this.nc=new z.xd(this);this.Yw=new z.xd(this);this.Eb=new Sp;this.YI=-1};\n" +
                "var Ls=function(a,b,c){if(z.ja(c)?c:a.Rm){c=Ms(a,a.X(),z.Fs(a.ob)[0]);var d=Ns(a,a.X());a.dY.test(b)||(b=z.op(b)+a.fQ);a.JZ&&(0==c||z.tp(d[c-1])||(b=\" \"+b),c==d.length-1&&(b+=\" \"));if(b!=d[c]){d[c]=b;b=a.ob;(z.B||z.C&&z.E(\"9\"))&&b.blur();b.value=d.join(\"\");for(var f=0,g=0;g<=c;g++)f+=d[g].length;b.focus();c=f;d=a.ob;b=c;Gs(d)?d.selectionStart=b:z.C&&(f=Hs(d),g=f[0],g.inRange(f[1])&&(b=Js(d,b),g.collapse(!0),g.move(\"character\",b),g.select()));d=a.ob;Gs(d)?d.selectionEnd=c:z.C&&(f=Hs(d),b=f[1],f[0].inRange(b)&&\n" +
                "(c=Js(d,c),d=Js(d,z.Fs(d)[0]),b.collapse(!0),b.moveEnd(\"character\",c-d),b.select()))}}else a.Da(b);a.rC=!0};var Os=function(a,b){var c=a.Rm&&b.charCode&&-1!=a.Qq.indexOf(String.fromCharCode(b.charCode));a.fY&&c&&a.update();return a.eY&&c&&a.Y.ij()?(b.preventDefault(),!0):!1};var Ps=function(a){a.Eb.attach(a.ob);a.nc.g(a.Eb,\"key\",a.tq);a.nc.g(a.ob,\"mousedown\",a.gK);z.C&&a.nc.g(a.ob,\"keypress\",a.dK)};\n" +
                "var Qs=function(a,b){a.Yw.removeAll();a.Y&&z.Ds(a.Y);b!=a.ob&&(a.ob=b,a.la&&(a.la.start(),a.nc.g(a.la,\"tick\",a.wq)),a.Vp=a.X(),Ps(a))};var Rs=function(a){a.uj&&(a.uj=!1,a.nc.oa(a.ob,\"keypress\",a.eK),a.nc.oa(a.ob,\"keyup\",a.fK))};var Ms=function(a,b,c){a=Ns(a,b);if(c==b.length)return a.length-1;for(var d=b=0,f=0;d<a.length&&f<=c;d++)f+=a[d].length,b=d;return b};\n" +
                "var Ns=function(a,b){if(!a.Rm)return[b];for(var c=String(b).split(\"\"),d=[],f=[],g=0,h=!1;g<c.length;g++)a.gJ&&-1!=a.gJ.indexOf(c[g])?(a.dR&&!h&&(d.push(f.join(\"\")),f.length=0),f.push(c[g]),h=!h):h||-1==a.Qq.indexOf(c[g])?f.push(c[g]):(f.push(c[g]),d.push(f.join(\"\")),f.length=0);d.push(f.join(\"\"));return d};z.Ss=function(a,b,c){z.xc.call(this);this.zD=a;this.GD=!b;this.da=new z.de(c)};\n" +
                "z.Ts=function(a,b,c,d,f,g,h,k,l){var p=Us(c),q=Eo(a),w=Ho(a);w&&q.uA(new z.sg(w.left,w.top,w.right-w.left,w.bottom-w.top));var w=z.Ie(a),I=z.Ie(c);if(w.wa()!=I.wa()){var K=w.wa().body;var I=I.bb(),O=new z.Ge(0,0),ba=z.Te(z.Ke(K));if(z.Oc(ba,\"parent\")){var Ua=K;do{var Sa=ba==I?z.$n(Ua):z.Gg(Ua);O.x+=Sa.x;O.y+=Sa.y}while(ba&&ba!=I&&ba!=ba.parent&&(Ua=ba.frameElement)&&(ba=ba.parent))}K=no(O,z.$n(K));!z.C||9<=z.Vg||Un(w)||(K=no(K,z.xf(w)));q.left+=K.x;q.top+=K.y}a=Vs(a,b);q=new z.Ge(a&2?q.left+q.width:\n" +
                "q.left,a&1?q.top+q.height:q.top);q=no(q,p);f&&(q.x+=(a&2?-1:1)*f.x,q.y+=(a&1?-1:1)*f.y);var ya;if(h)if(l)ya=l;else if(ya=Ho(c))ya.top-=p.y,ya.right-=p.x,ya.bottom-=p.y,ya.left-=p.x;return Ws(q,c,d,g,ya,h,k)};\n" +
                "var Us=function(a){var b;if(a=a.offsetParent){var c=\"HTML\"==a.tagName||\"BODY\"==a.tagName;c&&\"static\"==z.Ag(a)||(b=z.$n(a),c||(c=(c=z.Og(a))&&z.B?-a.scrollLeft:!c||z.Ll&&z.E(\"8\")||\"visible\"==z.zg(a,\"overflowX\")?a.scrollLeft:a.scrollWidth-a.clientWidth-a.scrollLeft,b=no(b,new z.Ge(c,a.scrollTop))))}return b||new z.Ge};\n" +
                "var Ws=function(a,b,c,d,f,g,h){a=a.clone();var k=Vs(b,c);c=z.Jg(b);h=h?h.clone():c.clone();a=a.clone();h=h.clone();var l=0;if(d||0!=k)k&2?a.x-=h.width+(d?d.right:0):d&&(a.x+=d.left),k&1?a.y-=h.height+(d?d.bottom:0):d&&(a.y+=d.top);if(g){if(f){d=a;k=h;l=0;65==(g&65)&&(d.x<f.left||d.x>=f.right)&&(g&=-2);132==(g&132)&&(d.y<f.top||d.y>=f.bottom)&&(g&=-5);d.x<f.left&&g&1&&(d.x=f.left,l|=1);if(g&16){var p=d.x;d.x<f.left&&(d.x=f.left,l|=4);d.x+k.width>f.right&&(k.width=Math.min(f.right-d.x,p+k.width-f.left),\n" +
                "k.width=Math.max(k.width,0),l|=4)}d.x+k.width>f.right&&g&1&&(d.x=Math.max(f.right-k.width,f.left),l|=1);g&2&&(l=l|(d.x<f.left?16:0)|(d.x+k.width>f.right?32:0));d.y<f.top&&g&4&&(d.y=f.top,l|=2);g&32&&(p=d.y,d.y<f.top&&(d.y=f.top,l|=8),d.y+k.height>f.bottom&&(k.height=Math.min(f.bottom-d.y,p+k.height-f.top),k.height=Math.max(k.height,0),l|=8));d.y+k.height>f.bottom&&g&4&&(d.y=Math.max(f.bottom-k.height,f.top),l|=2);g&8&&(l=l|(d.y<f.top?64:0)|(d.y+k.height>f.bottom?128:0));f=l}else f=256;l=f}g=new z.sg(0,\n" +
                "0,0,0);g.left=a.x;g.top=a.y;g.width=h.width;g.height=h.height;f=l;if(f&496)return f;z.Bg(b,new z.Ge(g.left,g.top));h=g.vh();z.Vo(c,h)||(c=h,a=Un(z.Ie(z.Ke(b))),!z.C||z.E(\"10\")||a&&z.E(\"8\")?(b=b.style,z.B?b.MozBoxSizing=\"border-box\":z.D?b.WebkitBoxSizing=\"border-box\":b.boxSizing=\"border-box\",b.width=Math.max(c.width,0)+\"px\",b.height=Math.max(c.height,0)+\"px\"):(h=b.style,a?(a=z.Rg(b),b=z.Ug(b),h.pixelWidth=c.width-b.left-a.left-a.right-b.right,h.pixelHeight=c.height-b.top-a.top-a.bottom-b.bottom):(h.pixelWidth=\n" +
                "c.wik.width=Math.max(k.width,0),l|=4)}d.x+k.width>f.right&&g&1&&(d.x=Math.max(f.right-k.width,f.left),l|=1);g&2&&(l=l|(d.x<f.left?16:0)|(d.x+k.width>f.right?32:0));d.y<f.top&&g&4&&(d.y=f.top,l|=2);g&32&&(p=d.y,d.y<f.top&&(d.y=f.top,l|=8),d.y+k.height>f.bottom&&(k.height=Math.min(f.bottom-d.y,p+k.height-f.top),k.height=Math.max(k.height,0),l|=8));d.y+k.height>f.bottom&&g&4&&(d.y=Math.max(f.bottom-k.height,f.top),l|=2);g&8&&(l=l|(d.y<f.top?64:0)|(d.y+k.height>f.bottom?128:0));f=l}else f=256;l=f}g=new z.sg(0,\n" +
                "\" +\n" +
                "                \"0,0,0);g.left=a.x;g.top=a.y;g.width=h.width;g.height=h.height;f=l;if(f&496)return f;z.Bg(b,new z.Ge(g.left,g.top));h=g.vh();z.Vo(c,h)||(c=h,a=Un(z.Ie(z.Ke(b))),!z.C||z.E(\\\"10\\\")||a&&z.E(\\\"8\\\")?(b=b.style,z.B?b.MozBoxSizing=\\\"border-box\\\":z.D?b.WebkitBoxSizing=\\\"border-box\\\":b.boxSizing=\\\"border-box\\\",b.width=Math.max(c.width,0)+\\\"px\\\",b.height=Math.max(c.height,0)+\\\"px\\\"):(h=b.style,a?(a=z.Rg(b),b=z.Ug(b),h.pixelWidth=c.width-b.left-a.left-a.right-b.right,h.pixelHeight=c.height-b.top-a.top-a.bottom-b.bottom):(h.pixelWidth=\\n\" +\n" +
                "                \"c.k.width=Math.max(k.width,0),l|=4)}d.x+k.width>f.right&&g&1&&(d.x=Math.max(f.right-k.width,f.left),l|=1);g&2&&(l=l|(d.x<f.left?16:0)|(d.x+k.width>f.right?32:0));d.y<f.top&&g&4&&(d.y=f.top,l|=2);g&32&&(p=d.y,d.y<f.top&&(d.y=f.top,l|=8),d.y+k.height>f.bottom&&(k.height=Math.min(f.bottom-d.y,p+k.height-f.top),k.height=Math.max(k.height,0),l|=8));d.y+k.height>f.bottom&&g&4&&(d.y=Math.max(f.bottom-k.height,f.top),l|=2);g&8&&(l=l|(d.y<f.top?64:0)|(d.y+k.height>f.bottom?128:0));f=l}else f=256;l=f}g=new z.sg(0,\n" +
                "\" +\n" +
                "                \"0,0,0);g.left=a.x;g.top=a.y;g.width=h.width;g.height=h.height;f=l;if(f&496)return f;z.Bg(b,new z.Ge(g.left,g.top));h=g.vh();z.Vo(c,h)||(c=h,a=Un(z.Ie(z.Ke(b))),!z.C||z.E(\\\"10\\\")||a&&z.E(\\\"8\\\")?(b=b.style,z.B?b.MozBoxSizing=\\\"border-box\\\":z.D?b.WebkitBoxSizing=\\\"border-box\\\":b.boxSizing=\\\"border-box\\\",b.width=Math.max(c.width,0)+\\\"px\\\",b.height=Math.max(c.height,0)+\\\"px\\\"):(h=b.style,a?(a=z.Rg(b),b=z.Ug(b),h.pixelWidth=c.width-b.left-a.left-a.right-b.right,h.pixelHeight=c.height-b.top-a.top-a.bottom-b.bottom):(h.pixelWidth=\\n\" +\n" +
                "                \"c.dth,h.pixelHeight=c.height)));return f};var Vs=function(a,b){return(b&4&&z.Og(a)?b^2:b)&-5};z.Xs=function(a,b,c,d){z.G.call(this);this.Ua=a||window.document.body;this.ca=z.Ie(this.Ua);this.Kq=!a;this.h=null;this.ec=\"\";this.Oa=[];this.gf=[];this.QL=this.Dm=-1;this.zb=!1;this.className=\"ac-renderer\";this.Uh=\"ac-row\";this.cJ=\"active\";this.Zw=\"ac-active\";this.eT=\"ac-highlighted\";this.Xl=b||null;this.JM=null!=d?d:!0;this.BU=!0;this.mp=!1;this.GX=!!c;this.gw=!1;this.fq=0;this.KL=!1};\n" +
                "var Ys=function(a,b){a.Lc&&(z.dj(a.Lc,\"haspopup\",b),z.dj(a.h,\"expanded\",b),b?z.dj(a.Lc,\"owns\",a.h.id):(a.Lc.removeAttribute(\"aria-owns\"),Bo(a.Lc,null)))};var Zs=function(a,b){var c=0<=b&&b<a.Oa.length?a.Oa[b]:void 0,d=0<=b&&b<a.gf.length?a.gf[b]:void 0;a.dispatchEvent({type:\"rowhilite\",D0:d,gj:c?c.data:null})&&(0<=a.Dm&&z.lj(a.gf[a.Dm],[a.Zw,a.cJ]),a.Dm=b,d&&(z.jj(d,[a.Zw,a.cJ]),a.Lc&&Bo(a.Lc,d),Go(d,a.h)))};\n" +
                "var $s=function(a){if(!a.h){var b=a.ca.B(\"DIV\",{style:\"display:none\"});a.KL&&(b.style.overflowY=\"auto\");a.h=b;z.jj(b,(0,z.ab)(a.className).split(\" \"));z.cj(b,\"listbox\");b.id=z.Yg(z.Xg.ba());a.ca.appendChild(a.Ua,b);z.F(b,\"click\",a.sm,!1,a);z.F(b,\"mousedown\",a.tm,!1,a);z.F(b,\"mouseover\",a.BH,!1,a)}};\n" +
                "var at=function(a){$s(a);a.gw&&(a.h.style.visibility=\"hidden\");a.KZ&&(a.h.style.minWidth=a.KZ.clientWidth+\"px\");a.gf.length=0;a.ca.Jq(a.h);if(a.Xl&&a.Xl.render)a.Xl.render(a,a.h,a.Oa,a.ec);else{var b=null;z.A(a.Oa,function(a){a=bt(this,a,this.ec);this.gw?this.h.insertBefore(a,b):this.ca.appendChild(this.h,a);b=a},a)}0==a.Oa.length?a.Pc():(a.show(),a.ga(),z.Do(a.h,!0))};\n" +
                "var ct=function(a,b,c){if(a.mp||!a.WM)if(3==b.nodeType){var d=null;z.ma(c)&&1<c.length&&!a.mp&&(d=z.yb(c,1));c=dt(a,c);if(0!=c.length){var f=b.nodeValue,g=a.BU?new RegExp(\"\\\\b(?:\"+c+\")\",\"gi\"):new RegExp(c,\"gi\");c=[];for(var h=0,k=g.exec(f),l=0;k;)l++,c.push(f.substring(h,k.index)),c.push(f.substring(k.index,g.lastIndex)),h=g.lastIndex,k=g.exec(f);c.push(f.substring(h));if(1<c.length){d=a.mp?l:1;for(f=0;f<d;f++)g=2*f,b.nodeValue=c[g],h=a.ca.createElement(\"B\"),h.className=a.eT,a.ca.appendChild(h,a.ca.createTextNode(c[g+\n" +
                "1])),h=b.parentNode.insertBefore(h,b.nextSibling),b.parentNode.insertBefore(a.ca.createTextNode(\"\"),h.nextSibling),b=h.nextSibling;c=z.yb(c,2*d);b.nodeValue=c.join(\"\");a.WM=!0}else d&&ct(a,b,d)}}else for(b=b.firstChild;b;)d=b.nextSibling,ct(a,b,c),b=d};\n" +
                "var dt=function(a,b){var c=\"\";if(!b)return c;z.ma(b)&&(b=z.lb(b,function(a){return!z.tp(null==a?\"\":String(a))}));a.mp?z.ma(b)?c=z.mb(b,z.Xa).join(\"|\"):(c=b.replace(/[\\s\\xa0]+/g,\" \").replace(/^\\s+|\\s+$/g,\"\"),c=z.Xa(c),c=c.replace(/ /g,\"|\")):z.ma(b)?c=0<b.length?z.Xa(b[0]):\"\":/^\\W/.test(b)||(c=z.Xa(b));return c};\n" +
                "var bt=function(a,b,c){var d=a.ca(!b){b=this.constructor;for(var d;b;){d=z.ta(b);if(d=dq[d])break;b=b.v?b.v.constructor:null}b=d?z.qa(d.ba)?d.ba():new d:null}this.M=b;this.mn(z.ja(a)?a:null);this.RE=null};\n" +
                "var eq=function(a,b){var c=a.o(),d=a.m();b?(c.g(d,\"mouseover\",a.Gd).g(d,\"mousedown\",a.xe).g(d,\"mouseup\",a.Kf).g(d,\"mouseout\",a.vm),a.ep!=z.r&&c.g(d,\"contextmenu\",a.ep),z.C&&(c.g(d,\"dblclick\",a.tH),a.qp||(a.qp=new fq(a),z.Ac(a,a.qp)))):(c.oa(d,\"mouseover\",a.Gd).oa(d,\"mousedown\",a.xe).oa(d,\"mouseup\",a.Kf).oa(d,\"mouseout\",a.vm),a.ep!=z.r&&c.oa(d,\"contextmenu\",a.ep),z.C&&(c.oa(d,\"dblclick\",a.tH),z.Cc(a.qp),a.qp=null))};var Xp=function(a,b){return!!(a.mr&b)};\n" +
                "var gq=function(a,b){return!!(a.Gj&b)&&Xp(a,b)};var hq=function(a,b,c){return Xp(a,b)&&!!(a.N&b)!=c&&(!(a.bl&b)||a.dispatchEvent(Co(b,c)))&&!a.Xd};var fq=function(a){z.xc.call(this);this.Gs=a;this.xs=!1;this.ea=new z.xd(this);z.Ac(this,this.ea);a=this.Gs.h;this.ea.g(a,\"mousedown\",this.tm).g(a,\"mouseup\",this.Kt).g(a,\"click\",this.sm)};var iq=function(){};z.jq=function(a,b,c){cq.call(this,a,b||iq.ba(),c)};var kq=function(){};\n" +
                "var lq=function(a,b,c){if(b){var d=mq(a,c);z.hj(b,d)||(z.Db(nq,function(a){a=mq(this,a);z.yo(b,a,a==d)},a),z.dj(b,\"checked\",c==oq?\"mixed\":c==pq?\"true\":\"false\"))}};var mq=function(a,b){var c=a.V();if(b==pq)return c+\"-checked\";if(b==qq)return c+\"-unchecked\";if(b==oq)return c+\"-undetermined\";throw Error(\"Invalid checkbox state: \"+b);};var rq=function(a,b,c){c=c||kq.ba();cq.call(this,null,c,b);this.yi=z.ja(a)?a:qq};z.sq=function(){};var tq=function(){};\n" +
                "z.uq=function(a,b,c,d,f){function g(a){a&&(a.tabIndex=0,z.cj(a,h.Ef()),z.ij(a,\"goog-zippy-header\"),vq(h,a),a&&h.UI.g(a,\"keydown\",h.tV))}z.G.call(this);this.ca=f||z.Ie();this.ng=this.ca.m(a)||null;this.Xj=this.ca.m(d||null);this.cm=(this.tu=z.qa(b)?b:null)||!b?null:this.ca.m(b);this.vb=1==c;z.ja(c)||this.tu||(this.Xj?this.vb=z.Mg(this.Xj):this.ng&&(this.vb=z.hj(this.ng,\"goog-zippy-expanded\")));this.UI=new z.xd(this);this.mB=new z.xd(this);var h=this;g(this.ng);g(this.Xj);this.Jc(this.vb)};\n" +
                "var wq=function(a){var b=a.Xj;return b&&z.Mg(b)?b:a.ng};var vq=function(a,b){b&&a.mB.g(b,\"click\",a.sV)};var xq=function(a,b,c){z.Lc.call(this,a,b);this.sh=c};var yq=function(){z.U.call(this);this.De(!0)};var zq=function(a){var b=(0,window.$)(\".resend-activation-email\",a.YD);Aq(a,b,10,function(){window.$.post(\"/reactive\")})};\n" +
                "var Bq=function(a){window.$.get(\"/settings/account/request_unlock\");var b=(0,window.$)(\"form.send-code\",a.PD),c=a.MD=(0,window.$)(\"form.activate\",a.PD),d=(0,window.$)(\".submit\",b);b.validate(window.$.extend({},Cq,{submitHandler:z.uk(d,window.$.proxy(a.UV,a))}));b=(0,window.$)(\".submit\",c);c.validate(window.$.extend({},Cq,{submitHandler:z.uk(b,window.$.proxy(a.WU,a))}));b=(0,window.$)(\"button.resend-code\",c);Aq(a,b,60,function(){var a=(0,window.$)('input[name\\x3d\"account\"]',c).val();if(\"\"===a)return c.data(\"validator\").showErrors({account:\"请填写手机号或邮箱\"}),\n" +
                "!1;var b=this.af(a),d;b?(a={email:a},d=\"/settings/account/send_new_email_digits\"):(a={phone_no:a},d=\"/settings/account/send_new_phone_digits\");var k=this;window.$.post(d,a,function(a){a.success?Dq(k,b):(a=a.payload.fields,b?k.Fb(a,\"email\",\"account\"):k.Fb(a,\"phone_no\",\"account\"),c.data(\"validator\").showErrors(a))})})};var Dq=function(a,b){a.Ow||(a.Ow=(0,window.$)(\".tip\",a.Ha));b?a.Ow.html(\"验证码已发送至你的邮箱，请查收。\"):a.Ow.html(\"验证码已发送至你的手机，请查收。\")};\n" +
                "var Aq=function(a,b,c,d){var f=b.text();b=z.tk(b,c,function(a){return a?\"%s 秒后即可重发\":f},window.$.proxy(d,a));z.Ac(a,b)};\n" +
                "var Eq=function(a){function b(){(0,window.clearTimeout)(g);g=null;try{delete window[d]}catch(a){window[d]=null}}\"string\"===window.$.type(a)&&(a={url:a});a=a||{};var c=window.$.Deferred(),d=\"zh\"+(0,z.H)()+Yn(),f=window.$.extend({},a.data||{},{callback:d}),g=null;a.timeout&&(g=(0,window.setTimeout)(function(){window[d]&&(window[d]=b,c.reject(\"timeout\"))},a.timeout));window[d]=c.resolve;a=a.url+(-1===a.url.indexOf(\"?\")?\"?\":\"\\x26\")+window.$.param(f);z.eh(a).fail(c.reject).always(b);return c.promise()};\n" +
                "var Fq=function(a,b){b=void 0===b?0:b;z.G.call(this);this.EO=Object.assign({},Gq,a);this.JW=b;this.Av=1E3;this.uJ=3E4;this.mT=1.5};z.Hq=function(a,b){a=void 0===a?z.r:a;b=void 0===b?!1:b;z.Q.call(this);this.DB=a;this.pY=b};var Iq=function(a){window.$.get(\"/antispam/get_token\").then(function(b){a.token=b.token;a.timeout=b.ttl;a.startTime=Date.now();(0,window.$)(\".js-token\",a.h).text(a.token);(0,window.$)(\".js-timeout\",a.h).text((0,window.parseInt)(a.timeout/60))})};\n" +
                "var Jq=function(a){var b=(0,window.$)(\".js-sent\",a.h);b.click(z.uk(b,function(){if(Date.now()>a.startTime+1E3*a.timeout)return Iq(a),Kq(a,\"短信超时，请重新发送\");Lq(a);a.ql.show();return window.$.get(\"/antispam/is_send_sms\").then(function(b){b.is_send_sms?Mq(a,b.is_delay?\"appeal\":\"unblock\"):Kq(a,\"没收到正确的短信，请重新发送\");a.ql.hide()},function(){a.ql.hide()})}))};\n" +
                "var Nq=function(a){var b=(0,win";
        System.out.println(BFMatch(i, "apple"));
        System.out.println(KMPMatch(i, "apple"));
    }

    private static int BFMatch(String p, String t) {
        int n = p.length();
        int m = t.length();
        int j = 0;
        int k = 0;
        while (j < n && k < m) {
            if (p.charAt(j) == t.charAt(k)) {
                j++;
                k++;
            } else {
                j = j - k + 1;
                k = 0;
            }
        }
        return j - k;
    }

    private static int KMPMatch(String t, String p) {
        //文本串
        int n = t.length();
        int i = 0;
        //模式串
        int m = p.length();
        int j = 0;
        while (j < m && i < n) {
            if (j < 0 || p.charAt(j) == t.charAt(i)) {
                i++;
                j++;
            } else {

            }
        }
        return i - j;
    }
}
